### ISSUE TITLE
About the test of data loading & train

### ISSUE THREAD

**Issue by jiheeyang** [Arthur151/ROMP#105]
Hi, I have difficulty training your code or loading datasets.

Sorry, I don't know because I just started studying.

I'm going to use Google Colab to learn as you said in your docs (dataset.md, train.md) by

python -m romp.lib.dataset.lsp

or

sh scripts/V1_train.sh

But there seems to be a problem reading the data.

yaml_timestamp  /content/ROMP/active_configs/active_context_2021-11-24_11_15_34.yaml
Confidence: 0.2
configs_yml: /content/ROMP/configs/v1.yml
model_version: 1
test_projection_part: False
Initialized dataset
visualize in gpu mode
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/ROMP/romp/lib/dataset/lsp.py", line 91, in <module>
    test_dataset(dataset,with_smpl=True)
  File "/content/ROMP/romp/lib/dataset/image_base.py", line 492, in test_dataset
    for _,r in enumerate(dataloader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/ROMP/romp/lib/dataset/image_base.py", line 342, in __getitem__
    return self.get_item_single_frame(index)
  File "/content/ROMP/romp/lib/dataset/image_base.py", line 85, in get_item_single_frame
    info = self.get_image_info(index)
  File "/content/ROMP/romp/lib/dataset/lsp.py", line 67, in get_image_info
    image = cv2.imread(imgpath)[:,:,::-1]
TypeError: 'NoneType' object is not subscriptable

This problem occurs equally when testing the data loading, and other datasets too....

The dataset is here.

![image](https://user-images.githubusercontent.com/29176256/143228584-2577b76d-05fd-4476-ac98-edf4a2fb8f71.png)

![image](https://user-images.githubusercontent.com/29176256/143228625-d4cc63f8-6985-4cf4-bfb6-33c205669f03.png)

Can you help me with it?
Thanks

**Comment by Arthur151** [comment]
I see that you have set the datatsets in dataset folder. 
Please print the imgpath in 
`File "/content/ROMP/romp/lib/dataset/lsp.py", line 67, in get_image_info
image = cv2.imread(imgpath)[:,:,::-1]`
to see where it is leading to.

**Comment by jiheeyang** [comment]
Hi, I changed from Google Colab to Linux.
And the same problem occurs when training.

 File "/hdd1/YJH/romp_pytorch/ROMP/romp/lib/models/../utils/../dataset/h36m.py", line 92, in get_image_info
    image = cv2.imread(imgpath)[:,:,::-1]#把BGR转成RGB
TypeError: 'NoneType' object is not subscriptable

So  I printed out the imgpath, before  "image = cv2.imread(imgpath)[:,:,::-1]#把BGR转成RGB".
The output is as follows.

/export/home/suny/dataset/h36m/images/S5_Phoning 1_3_446.jpg


I have one more question.
I test the data loading of a dataset.
Other datasets except 'h36m' may perform a load test.
However, errors occur in most datasets while running.
'h36m'  dataset causes the above error.

 File "/hdd1/YJH/romp_pytorch/ROMP/romp/lib/dataset/image_base.py", line 498, in test_dataset
    img_bsname = os.path.basename(r['imgpath'][inds])
IndexError: list index out of range

**Comment by Arthur151** [comment]
Thanks for the bug report! I will fix this bug in next commit. 

About setting the dataset root path:
If you put all datasets in one folder, then you just need to change [this config](https://github.com/Arthur151/ROMP/blob/db299277b519de0970604789b4490d9f10318764/romp/lib/config.py#L151) to the path of your dataset folder, like:
```
dataset_group.add_argument('--dataset_rootdir',type=str, default='/path/to/your/dataset/folder', help= 'root dir of all datasets')
```
If you put different dataset at different path, then you have to set them separately. For instance, to set the path of Human3.6M dataset, please change [this line](https://github.com/Arthur151/ROMP/blob/db299277b519de0970604789b4490d9f10318764/romp/lib/dataset/h36m.py#L10) to the path where you put Human3.6M, like
```
self.data_folder = /path/to/your/h36m/
```

Please test the data loading after you fix the path problem above.
