### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Wyethjjj** [Arthur151/ROMP#131]
在调试程序的时候运行resnet主干训练lsp和测试的过程中都报了同样的错误，具体内容如下：
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data01/wyjh/ROMP/romp/train.py", line 149, in <module>
    main()
  File "/data01/wyjh/ROMP/romp/train.py", line 146, in main
    trainer.train()
  File "/data01/wyjh/ROMP/romp/train.py", line 34, in train
    self.train_epoch(epoch)
  File "/data01/wyjh/ROMP/romp/train.py", line 81, in train_epoch
    for iter_index, meta_data in enumerate(self.loader):
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 71, in __getitem__
    annots = self.datasets[inds][index_sample]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 342, in __getitem__
    return self.get_item_single_frame(index)
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 85, in get_item_single_frame
    info = self.get_image_info(index)
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/lsp.py", line 67, in get_image_info
    image = cv2.imread(imgpath)[:,:,::-1]
TypeError: 'NoneType' object is not subscriptable
以上是运行resnet主干训练lsp时的报错，测试的时候基本一样，只不过在这里是lsp.py的第67行，而测试的时候是pw3d.py的第124行。我想知道我应该如何去解决这个错误，希望作者能给我一些指点，谢谢您！

**Comment by Arthur151** [comment]
这个错误很明显，就是没有成功加载图片。
两个可能，一个是imgpath不对，这种一运行就会报错，你可以检查一下imgpath确认一下；
另一个原因就是可能某张图片缺失了导致的，这种运行一会才会报错，你可以通过以下代码调试。
```
try:
    image = cv2.imread(imgpath)[:,:,::-1]
except:
    print('{} missing'.format(imgpath))
    image = np.zeros((512,512,3))

```

**Comment by Wyethjjj** [comment]
作者新年好！
其实我感觉还是数据集位置的问题，我目前的数据集路径为/data01/wyjh/dataset/（与ROMP同级），并且在config.py里设置的路径为dataset_group.add_argument('--dataset_rootdir',type=str, default='/data01/wyjh/dataset/', help= 'root dir of all datasets')，然而运行程序时所走的路径为/data01/wyjh/ROMP/romp/lib/dataset/。
这个问题我觉得改路径就好了，可是之前我把dataset放在lib中运行的时候，运行报错在/data01/wyjh/中找不到dataset，我想请教作者指点我哪一步弄错了，或者少设置了什么东西。

**Comment by Arthur151** [comment]
新年好！
`然而运行程序时所走的路径为/data01/wyjh/ROMP/romp/lib/dataset/`,这个很奇怪啊。
config里的设置是最先在[这里](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L33)的数据集父类调用，可以在每个数据集子类里通过重新定义复写这个预定义，例如[这里](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/h36m.py#L10)。您如果清楚了这个赋值流程，应该可以搞清楚为什么会有这么奇怪的情况了~

**Comment by Wyethjjj** [comment]
作者您好，我通过您所提供的方式进行尝试并发现了问题所在：缺少图片，重新下载并导入数据集问题得到解决。
