### ISSUE TITLE
How to control vedo windows shape?

### ISSUE THREAD

**Issue by jinfagang** [Arthur151/ROMP#133]
![image](https://user-images.githubusercontent.com/21303438/147671374-ea029e53-c522-42cb-b6f9-9cfd843706f8.png)

Hi, default is 1960x1960, I make scaled to 1 rather than 2.
I want it to be rectangle window, how to controll it?

**Comment by Arthur151** [comment]
Here is the [instruction](https://vedo.embl.es/autodocs/content/vedo/plotter.html?highlight=plotter#vedo.plotter.Plotter) to change [this line](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/visualization/vedo_visualizer.py#L66)

**Comment by jinfagang** [comment]
@Arthur151 I make it to rectangle, it becomes like this:

![image](https://user-images.githubusercontent.com/21303438/147675775-ce4d49e6-e711-4b74-807d-851d53c1bc1c.png)

```
plt = Plotter(bg=[240, 255, 255], size=(600, 800), axes=0,
                      offscreen=not interactive_show)
```

**Comment by Arthur151** [comment]
I have tested that the right way to achieve this is to change [this line](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/visualization/vedo_visualizer.py#L94) from ```image_result = plt.show(camera=self.default_camera)``` to `image_result = plt.show(camera=self.default_camera, size=(800,600))`

**Comment by jinfagang** [comment]
@Arthur151 Hi, I changed that line, but I can not got expected result?

![image](https://user-images.githubusercontent.com/21303438/147717142-e3d88bd0-de6d-4fdc-9c71-1c7f1bb3f5b7.png)


Also Plotter size params order is H, W， you set to (800, 600), how do u get a rectanlge like above? your height should bigger than width.

**Comment by Arthur151** [comment]
Hi,   @jinfagang  Bro~
Please set the Plotter back to `plt = Plotter(size=(h,w),bg=[240,255,255], axes=0, offscreen=not interactive_show)`, change the line I metioned above only.


> I am back. Hi, @jinfagang I have tested that the right way to achieve this is to change [this line](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/visualization/vedo_visualizer.py#L94) from `image_result = plt.show(camera=self.default_camera)` to `image_result = plt.show(camera=self.default_camera, size=(800,600))` ![image](https://user-images.githubusercontent.com/17900300/147715504-9cf974fc-fd59-4750-88d9-fa548983b0f5.png)

**Comment by jinfagang** [comment]
@Arthur151 I was set it back and only set size in plt.show.. 

I found the problem.

the vedo actually can get rectangle vis when set like yours. But what I vis is the result image get back from plt. It just messed up like I posted. Do you know how to get the normal rectangle from plt back?

**Comment by jinfagang** [comment]
@Arthur151 Oh, I get it. It was a mistake in reshape plt returned image back to cv2 image. the cols and rows are oppsited, you are using rectangle so you didn't get into this error. I fixed it.

**Comment by jinfagang** [comment]
@Arthur151 btw, do you know how to adjust the camera:

```
self.default_camera = {'pos': {'far': (0, 800, 1000), 'close': (0, 200, 800)}[
            args().soi_camera]}
```

I want the bottom plane image more flat, just like I view human on the right front view, do you know which params should adjust?

**Comment by Arthur151** [comment]
You can change the `'far': (0, 800, 1000)` to other coords. Assuming that people locate at the origin (0,0,0), you can change the camera location from (0, 800, 1000) to other values. Just try~
If possible, please leave the camera location that you perfer in convenience of other developers~

**Comment by jinfagang** [comment]
@Arthur151 Sure.

![image](https://user-images.githubusercontent.com/21303438/147726457-ff45ee8e-7db4-4571-95fe-533de2c608b2.png)

```
self.default_camera = {'pos': {'far': (-200, 600, 800), 'close': (0, 200, 800)}[
            args().soi_camera]}
```

![image](https://user-images.githubusercontent.com/21303438/147726772-d94b78b1-ffe3-4a26-a4ee-bbc041ce09f6.png)


```
self.default_camera = {'pos': {'far': (-200, 200, 800), 'close': (0, 200, 800)}[
            args().soi_camera]}
```

**Comment by jinfagang** [comment]
@Arthur151 I have serveral questoin about the ROMP method, could you help me figure it out?

1. In paper, it says using 22 joints instead original 24 in SMPL, drops 2 hand joints, for what consideration do that?
2. the SMPL map outputs a shape of 142xHxW, 22x6=132, where is the rest 10 dimension represents?
3. (might not related to romp): the SMLP wrapper model, it seems doesn't have any params, why it using nn.Module? Is the able change to a single method? It looks like simply some vertices index operation which can be done using torch.index_select or something?

**Comment by Arthur151** [comment]
Of course! Good question!
Q1. The dropped paramereters of 2 hand joints describe the 3D hand posture, which is not estimated by ROMP. So we drop them. 
Q2. The rest 10 dimension represents the 3D body shape of SMPL statistical model. 
Q3. SMPL model contains some fixed statistical parameters describing the pose prior space, the shape piror space, the joint regressor, and e.t.c. It is defined as nn.Module, because it is used as a layer during model training. Gradients flow though this layer.

**Comment by jinfagang** [comment]
@Arthur151 so does the registered tensor buffer actually will update params?

btw, I am not very famillar with smpl acutally, newbie here. I wanna ask, if I want do mesh estimation via TopDown approach, rather then E2E, I have get 2d keypoints, then how should I use them get mesh? (Can u give me dedicated flows and method in them?)

**Comment by Arthur151** [comment]
No, it won't update params.

I recommand to read [our survey paper](https://arxiv.org/abs/2104.11536).

**Comment by jinfagang** [comment]
@Arthur151 thank u so much. 

I have on last question wanna ask. Do u know how to run that script `convert_fbx.py` file?

I currently unable install bpy locally, except I directly import from blender python console.

It gives me this error:

![image](https://user-images.githubusercontent.com/21303438/147758886-76434fd8-1b15-40fc-89df-37035909e89d.png)

**Comment by Arthur151** [comment]
Error report is just fine. It still gives you the right fbx file.

**Comment by Arthur151** [comment]
@jinfagang Brother Tian~ I get some feedbacks from Vedo developers.
They recommand to refer [this example](https://github.com/marcomusy/vedo/blob/master/examples/advanced/timer_callback1.py). It seems quite simple.

**Comment by jinfagang** [comment]
@Arthur151 thank u! this seems a solution.

I got one last final problem to make blender run, would u help me figure out why? 

```
>>> a = bpy.data.objects['Armature.001'].data
>>> a.edit_bones('m_avg_Pelvis')
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
TypeError: 'bpy_prop_collection' object is not callable

>>> bpy.ops.object.mode_set(mode='EDIT')
{'FINISHED'}

>>> pb = a.edit_bones['m_avg_Pelvis']
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "m_avg_Pelvis" not found'

>>> a.bones.keys()
['m_avg_root', 'm_avg_Pelvis', 'm_avg_L_Hip', 'm_avg_L_Knee', 'm_avg_L_Ankle', 'm_avg_L_Foot', 'm_avg_R_Hip', 'm_avg_R_Knee', 'm_avg_R_Ankle', 'm_avg_R_Foot', 'm_avg_Spine1', 'm_avg_Spine2', 'm_avg_Spine3', 'm_avg_Neck', 'm_avg_Head', 'm_avg_L_Collar', 'm_avg_L_Shoulder', 'm_avg_L_Elbow', 'm_avg_L_Wrist', 'm_avg_L_Hand', 'm_avg_R_Collar', 'm_avg_R_Shoulder', 'm_avg_R_Elbow', 'm_avg_R_Wrist', 'm_avg_R_Hand']

```

I am really confused by this, it raise error like this:

```
KeyError: 'bpy_prop_collection[key]: key "m_avg_Pelvis" not found'
错误: Python 脚本失败，请检查系统控制台中的消息

```

But as you can see above, I printed bpy object data bones keys, it just exist. Do u know how to avoid this error?

**Comment by jinfagang** [comment]
Oh. I solved it by remove all other Amatures. 

I currently can make smpl model move:

![image](https://user-images.githubusercontent.com/21303438/147846106-b355296f-0e68-454c-bcad-c326e1ce5744.png)

but, How can I apply these fbx to another new model?

**Comment by Arthur151** [comment]
Now we are on the stage. We are facing the same problem.
Get Outlook for Android

**Comment by jinfagang** [comment]
@Arthur151 Bro, don't joke me, you already make some amazing effect drive new charactors realtime in your webcam demo. Do u know how to drive them? For example, some fbx models download from here: https://www.mixamo.com/#/

**Comment by Arthur151** [comment]
I am not joking. We are working on this stage too. The demo of driving another character is not implement by technical method. It just bind the skeleton from SMPL to the other character by hand with the help of some engineers. My colleages are developing the automatic retargeting now. I am in charge of developing better ROMP, not retargeting thing. I don't know nuch about retargeting. Sorry for that.
Get Outlook for Android

**Comment by jinfagang** [comment]
@Arthur151 so the demo actually doesn't runs in realtime and automatic right?

**Comment by Arthur151** [comment]
With a character that have similar skeleton with SMPL, the demo can run in real time. Otherwise, it won't. That part is not the focus of this project. There might be  other rep. that can achieve this.
Get Outlook for Android

**Comment by jinfagang** [comment]
@Arthur151 But, I still don't know, how do u sync the fbx animation to target charactor, since you have to manually retargeting it right ? How to automatic that process?

**Comment by jinfagang** [comment]
@Arthur151  Brother, I found for models download from mixamo, the bones names are not same as SMPL. Do u know where to download the same charactor as your demo, which can direclty mapping animations from SMPL fbx to charactores?
![image](https://user-images.githubusercontent.com/21303438/147879643-bd793dd6-54b4-478c-9a02-cf477523fd6f.png)

**Comment by jinfagang** [comment]
@Arthur151  Hi, Brother. I found when I run webcam.sh, it was stucked:

![image](https://user-images.githubusercontent.com/21303438/147880987-08fd0256-2a35-4542-bc39-8e59010487c1.png)

Seems socket can not be established to Blender, does there any recevier need to installed or enabled on blender side?

**Comment by Arthur151** [comment]
Yes, [here](https://github.com/Arthur151/ROMP/blob/master/docs/export.md#blender-character-animation) is the instruction. [This repo](https://github.com/yanch2116/CharacterDriven-BlenderAddon) from my colleague might helps. He knows Blender better.

**Comment by jinfagang** [comment]
@Arthur151 thanks. Do u have a wechat group or QQ group to talk about ROMP? I really want to communicate about it.

**Comment by Arthur151** [comment]
Sure, my wechat account is 
sy936605403
