### ISSUE TITLE
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-21t5esfk/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) _step >= minstep in function 'Mat'

### ISSUE THREAD

**Issue by Wyethjjj** [Arthur151/ROMP#139]
作者您好，我在训练的过程中遇到了如下错误：cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-21t5esfk/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) _step >= minstep in function 'Mat'
具体情况是，我之前训练mpii和crowdpose时，在第五次迭代后报了这个错误，后来又跑了一次，在第24代报了这个错误，今天训练coco之后的第五次迭代报了这个错误。具体报错如下：
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data01/wyjh/ROMP/romp/train.py", line 149, in <module>
    main()
  File "/data01/wyjh/ROMP/romp/train.py", line 146, in main
    trainer.train()
  File "/data01/wyjh/ROMP/romp/train.py", line 34, in train
    self.train_epoch(epoch)
  File "/data01/wyjh/ROMP/romp/train.py", line 81, in train_epoch
    for iter_index, meta_data in enumerate(self.loader):
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/omnisky/wyj/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 71, in __getitem__
    annots = self.datasets[inds][index_sample]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 342, in __getitem__
    return self.get_item_single_frame(index)
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 98, in get_item_single_frame
    image, dst_image, org_image = self.prepare_image(image, image_wbg, augments=(color_jitter, syn_occlusion))
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 230, in prepare_image
    dst_image = cv2.resize(image, tuple(self.input_shape), interpolation = cv2.INTER_CUBIC)
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-21t5esfk/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) _step >= minstep in function 'Mat'
我想的是要不要换一下opencv版本，说不定能有效果，但还是想听听作者的指导，谢谢您！

**Comment by Arthur151** [comment]
这个报错我也有点困惑，我这里没遇到过，但确实有不止一两个人遇到过这个问题。其实就是`image`这个变量到cv2.resize这里变成None了。有其他人反馈说，这个小概率事件可能是因为[crop的时候](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/utils/augments.py#L203)截没了，就是bounding box的宽度可能是0，没有加约束，我新提交了commit，加上这个约束，就是把`r=max(cx,cy)`改成`r=max(cx,cy,1)`。
当然为了避免不是这里的原因，还是可以用try: except:确保一定可以运行。
```
try:
    dst_image = cv2.resize(image, tuple(self.input_shape), interpolation = cv2.INTER_CUBIC)
    org_image = cv2.resize(image_wbg, (self.vis_size, self.vis_size), interpolation=cv2.INTER_CUBIC)
except:
    dst_image = np.zeros((self.input_shape[0], self.input_shape[1], 3))
    org_image = np.zeros((self.vis_size, self.vis_size, 3))
```

**Comment by Wyethjjj** [comment]
好的作者，我试试看，有进展了给您回复

**Comment by Arthur151** [comment]
@Wyethjjj 好的，谢谢bug report。遇到这类问题可以及时和我说，我试着解决，解决不了也可以给个可以顺利运行程序的方案，而且其他朋友有类似的问题也有处参考。

**Comment by Wyethjjj** [comment]
作者您好，按照您所提示的方案进行修改，到目前没有再出现过这种情况，谢谢您！
