### ISSUE TITLE
lsp与mpiinf数据集问题

### ISSUE THREAD

**Issue by Wyethjjj** [Arthur151/ROMP#150]
作者您好，您所提供的7个数据集中我有两个训练有问题，皆为FileNotFoundError。

**其中lsp的报错如下：**
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data01/wyjh/ROMP/romp/train.py", line 149, in <module>
    main()
  File "/data01/wyjh/ROMP/romp/train.py", line 145, in main
    trainer = Trainer()
  File "/data01/wyjh/ROMP/romp/train.py", line 14, in __init__
    self.loader = self._create_data_loader(train_flag=True)
  File "/data01/wyjh/ROMP/romp/base.py", line 133, in _create_data_loader
    datasets = MixedDataset(train_flag=train_flag)
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 36, in __init__
    self.datasets = [dataset_dict[ds](**kwargs) for ds in datasets_used]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 36, in <listcomp>
    self.datasets = [dataset_dict[ds](**kwargs) for ds in datasets_used]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/lsp.py", line 11, in __init__
    self.load_data()
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/lsp.py", line 38, in load_data
    self.load_eft_annots(os.path.join(config.project_dir, 'data/eft_fit/LSPet_ver01.json'))
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/lsp.py", line 44, in load_eft_annots
    annots = json.load(open(annot_file_path,'r'))['data']
FileNotFoundError: [Errno 2] No such file or directory: '/data01/wyjh/ROMP/data/eft_fit/LSPet_ver01.json'
（不知道为什么会去data里找这个文件，我并没有data这个路径）

**mpiinf的报错如下：**
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/omnisky/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data01/wyjh/ROMP/romp/train.py", line 149, in <module>
    main()
  File "/data01/wyjh/ROMP/romp/train.py", line 145, in main
    trainer = Trainer()
  File "/data01/wyjh/ROMP/romp/train.py", line 14, in __init__
    self.loader = self._create_data_loader(train_flag=True)
  File "/data01/wyjh/ROMP/romp/base.py", line 133, in _create_data_loader
    datasets = MixedDataset(train_flag=train_flag)
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 36, in __init__
    self.datasets = [dataset_dict[ds](**kwargs) for ds in datasets_used]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 36, in <listcomp>
    self.datasets = [dataset_dict[ds](**kwargs) for ds in datasets_used]
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mpi_inf_3dhp.py", line 17, in __init__
    self.pack_data(annots_file_path)
  File "/data01/wyjh/ROMP/romp/lib/models/../utils/../dataset/mpi_inf_3dhp.py", line 111, in pack_data
    annot2 = sio.loadmat(annot_file_path)['annot2']
  File "/home/omnisky/wyj/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 224, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/home/omnisky/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/omnisky/wyj/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/home/omnisky/wyj/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/data01/wyjh/ROMP/romp/lib/dataset/mpi_inf_3dhp/S1/Seq1/annot.mat'
（同样，mpi_inf_3dhp中也没有S1这个文件夹）

我试着找了官网所提供的数据集发现并没有所缺内容，希望作者可以给我指点一下解决问题的方向。谢谢您！

**Comment by Arthur151** [comment]
您好，关于这两个问题：
1.LSP数据集：
请下载[这个数据包](https://github.com/Arthur151/ROMP/releases/download/v1.1/model_data.zip)，就有相关数据了。
2.mpi_inf_3dhp数据集：
它的文件应该是：
|   |-- mpi-inf-3dhp
|   |   |-- images
|   |   |-- annots.npz
您没有下载annots.npz，或者放的位置不对，导致程序没有找到。
建议您检查一下[这个路径](https://github.com/Arthur151/ROMP/blob/02b9d1d8fe6a9797ea0c25ce75c83c975133dee8/romp/lib/dataset/mpi_inf_3dhp.py#L11)是否正确。

**Comment by Wyethjjj** [comment]
我把您说的数据包下载了，放在了LSP文件下；mpiinf也按照您所提示的进行了核对，没有问题，但是现在我没有显卡可以用所以只能等等了，有进展了我会再回复您。

跨考后选择了这个方向，完全就是个小白，我对您的工作特别感兴趣，正是您的不断指点我才走到这里，之前问了很多问题您都十分有耐心的解答，有些问题现在看来是真的蠢，包括现在问的也是，真的很感谢您！您的工作创新性十足，我相信您之后的工作也一定会分量十足，祝您博士期间生活顺利、科研顺利！

最后，新年快乐！

**Comment by Wyethjjj** [comment]
作者您好，在您的帮助下，我解决了以上两个问题，解决方法分别为：1、重新设置了lsp中eft_annots.npz的路径，出现#131所提到的问题；2、将mpi-inf-3dhp文件名改为mpi_inf_3dhp然后就好使了。

**Comment by hust-kevin** [comment]
@Arthur151 你好，请问下你有使用原始版本的LSP 2000张图片训练么，因为我想看看romp在未知数据集上的效果

**Comment by Arthur151** [comment]
ROMP训练使用的hr-lspet，应该就是原始版本图片的高清版吧。。

**Comment by hust-kevin** [comment]
hr-lspet是1w张图片，lsp是2000张，请问lsp是hr-lspnet的子集嘛

**Comment by Arthur151** [comment]
我大概记得，hr-lspet是(lsp + lsp_extend)的图片的高分辨率版。

**Comment by hust-kevin** [comment]
对的，lsp和lspet都有对应的高清版本，那lsp这2000张应该不在lspet里面把，我看一些介绍好像也没有说的特别清楚，不知道lspet是在原本lsp2000的基础上扩充了8000张得到lspet，还是全新的1w张图片

**Comment by Arthur151** [comment]
是啊。我看了一下，只能确定同一id的图片不一样，不确定是不是扩充了。不过lsp数据集的图片都挺难的，哈哈哈。

**Comment by xjchao7** [comment]
> 您好，关于这两个问题： 1.LSP数据集： 它的文件是： | |-- lsp | | |-- hr-lspet | | | |-- eft_annots.npz 请检查一下[这行](https://github.com/Arthur151/ROMP/blob/02b9d1d8fe6a9797ea0c25ce75c83c975133dee8/romp/lib/dataset/lsp.py#L34)的eft_annots.npz的路径是否正确。 请下载eft_annots.npz，并放到hr-lspet里 2.mpi_inf_3dhp数据集： 它的文件应该是： | |-- mpi-inf-3dhp | | |-- images | | |-- annots.npz 您没有下载annots.npz，或者放的位置不对，导致程序没有找到。 建议您检查一下[这个路径](https://github.com/Arthur151/ROMP/blob/02b9d1d8fe6a9797ea0c25ce75c83c975133dee8/romp/lib/dataset/mpi_inf_3dhp.py#L11)是否正确。
> 
> 新年快乐

你好，我在处理mpi_inf_3dhp数据集是子目录没有images文件夹，而是S1，S2的序列文件夹，里面是视频。想问下如何可以得到所示的images文件夹。同时还想问下MuCO数据集是如何获得augmented_set的文件夹的。感谢。
