### ISSUE TITLE
Error in Google Colab demo

### ISSUE THREAD

**Issue by XXZhe** [Arthur151/ROMP#154]
when testing the demo video on google colab using the command:

```
% cd /content/ROMP
! python -m romp.predict.video --inputs=demo/videos/sample_video.mp4 --output_dir=demo/sample_video_results --save_visualization_on_img --save_dict_results  --renderer=pytorch3d
```

I got the following error.

```
/content/ROMP
No configs_yml is set, set it to the default --configs_yml=configs/video.yml
yaml_timestamp  /content/ROMP/active_configs/active_context_2022-02-10_22_40_05.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/ROMP/romp/predict/video.py", line 7, in <module>
    from .image import *
  File "/content/ROMP/romp/predict/image.py", line 7, in <module>
    from .base_predictor import *
  File "/content/ROMP/romp/predict/base_predictor.py", line 1, in <module>
    from ..base import *
  File "/content/ROMP/romp/base.py", line 25, in <module>
    from visualization.visualization import Visualizer
  File "/content/ROMP/romp/lib/models/../utils/../visualization/visualization.py", line 23, in <module>
    from .web_vis import write_to_html, convert_3dpose_to_line_figs, convert_image_list
  File "/content/ROMP/romp/lib/models/../utils/../visualization/web_vis.py", line 5, in <module>
    import plotly.express as px
  File "/usr/local/lib/python3.7/dist-packages/plotly/express/__init__.py", line 15, in <module>
    from ._imshow import imshow
  File "/usr/local/lib/python3.7/dist-packages/plotly/express/_imshow.py", line 11, in <module>
    import xarray
  File "/usr/local/lib/python3.7/dist-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/usr/local/lib/python3.7/dist-packages/xarray/tutorial.py", line 13, in <module>
    from .backends.api import open_dataset as _open_dataset
  File "/usr/local/lib/python3.7/dist-packages/xarray/backends/__init__.py", line 6, in <module>
    from .cfgrib_ import CfGribDataStore
  File "/usr/local/lib/python3.7/dist-packages/xarray/backends/cfgrib_.py", line 16, in <module>
    from .locks import SerializableLock, ensure_lock
  File "/usr/local/lib/python3.7/dist-packages/xarray/backends/locks.py", line 13, in <module>
    from dask.distributed import Lock as DistributedLock
  File "/usr/local/lib/python3.7/dist-packages/dask/distributed.py", line 3, in <module>
    from distributed import *
  File "/usr/local/lib/python3.7/dist-packages/distributed/__init__.py", line 3, in <module>
    from . import config
  File "/usr/local/lib/python3.7/dist-packages/distributed/config.py", line 20, in <module>
    defaults = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
```

Any help would be appreciated.

**Comment by Arthur151** [comment]
I will fix this as soon as possibleGet Outlook for Android

**Comment by XXZhe** [comment]
Thank you!

**Comment by Arthur151** [comment]
@XXZhe Problem fixed!
The bug is caused by the latest version of PyYAML is not supported by Google colab. I have assign the capatible version of pyYAML in requirement.txt to fix this. 
Sorry for the bug. Enjoy your day~

**Comment by Arthur151** [comment]
@XXZhe , I have also fixed the notebook part. Now, ROMP can be called via python code as a package to process image / video.
