### ISSUE TITLE
smpl_mesh_root_align

### ISSUE THREAD

**Issue by ZhengdiYu** [Arthur151/ROMP#158]
Hi, I notice that your **ROMP_HRNet_32.pkl** was trained on `smpl_mesh_root_align=False`. But in **v1.yml**, smpl_mesh_root_align is not set, so it's default value True.

So My questions are: 

1. (**Solved✔**) Firstly I found my model perform very bad visualization, then I found the reason: Image.yml is designed for ROMP_HRNet_32.pkl, which was trained on smpl_mesh_root_align=False. If we want to test on image using our model trained from pre-trained model using hrnet and v1.yml, the smpl_mesh_root_align in image.yml should also be set to `True`, just like resnet #106 . So this was solved.

2. When should smpl_mesh_root_align be True or False? Why did you set it to True for v1.yml and resnet, although it's false for ROMP_HRNet_32.pkl? I think for 3D joints loss, it doesn't matter as long as we would do another alignment before calculating MPJPE/PAMPJPE. And for the 2D part, the **weak camera parameters** will be automatically learnt to project those 3D joints to align with GT_2d as long as it's consistent all the time. ~So the last question is:

3. During **fine-tuning** from your model: **ROMP_HRNet_32.pkl using v1_hrnet_3dpw_ft.yml**. the smpl_mesh_root_align is also default value `True`, However, **ROMP_HRNet_32.pkl** was trained with `smpl_mesh_root_align=True`. 

As we know from question1: if we use different setting of smpl_mesh_root_align, the visualization will be shifted, I think this could be a problem for training and fine-tuning.

And I tried to train with smpl_mesh_root_align **from scratch**, but it's ended up with error below:
```
Traceback (most recent call last):
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 148, in <module>
    main()
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 145, in main
    trainer.train()
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 33, in train
    self.train_epoch(epoch)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 94, in train_epoch
    self.train_log_visualization(outputs, loss, run_time, data_time, losses, losses_dict, epoch, iter_index)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 74, in train_log_visualization
    vis_cfg={'settings': ['save_img'], 'vids': vis_ids, 'save_dir':self.train_img_dir, 'save_name':save_name, 'verrors': [vis_errors], 'error_names':['E']})
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/../utils/../visualization/visualization.py", line 102, in visulize_result
    rendered_imgs = self.visualize_renderer_verts_list(per_img_verts_list, images=org_imgs.copy(), trans=mesh_trans)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/../utils/../visualization/visualization.py", line 62, in visualize_renderer_verts_list
    rendered_img = self.renderer(verts, faces, colors=color, focal_length=args().focal_length, cam_params=cam_params)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/../utils/../visualization/renderer_pt3d.py", line 102, in __call__
    images = self.renderer(meshes)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/pytorch3d/renderer/mesh/renderer.py", line 59, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 168, in forward
    meshes_proj = self.transform(meshes_world, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 147, in transform
    verts_world, eps=eps
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/pytorch3d/transforms/transform3d.py", line 336, in transform_points
    points_out = _broadcast_bmm(points_batch, composed_matrix)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/pytorch3d/transforms/transform3d.py", line 753, in _broadcast_bmm
    return a.bmm(b)
RuntimeError: expected scalar type Half but found Float
```

I'm still debugging anyway.

**Comment by ZhengdiYu** [comment]
> Thanks~ About your questions: 2. Either way is OK, you are right about this. 3. This bug is pretty easy to fix. It is caused by the multipliation between different data type (Half and Float). Please check the data type where bug occured and set them to .float(). The easiest way is to set all outputs with .float(), which I have done in released code. There must be some changes in your code, please set these outputs to float.

1. I understand that it should be consistent. This is what I exactly want to say. The problem is that it doesn't seem to be consistent in your current training guidance. It didn't mention that we should change smpl_mesh_root_align to False when fine-tuning your ROMP_HRNet_32.pkl.

2. I do understand it's caused by what as it's clearly written in the log. What really confused me was that I didn't do any change to your code, except setting smpl_mesh_root_align to False, I was trying to reproduce the results all the time so I won't change your code but only settings. This error only occurs when I set smpl_mesh_root_align to False.

**Comment by ZhengdiYu** [comment]
> Thanks for your great work. About the bugs,
> 
> 1. It may not be well solved. ROMP_HRNet_32.pkl is kept for replementing some previous results.
> 2. Thanks for your work. I have fixed it at [this line](https://github.com/Arthur151/ROMP/blob/71a44bee87006a9c10bc6dcd99e0cb7b836ba427/romp/lib/models/smpl.py#L571) in last commit. Next time, could you please submit a pull request to fix it?
> 3. The [design](https://github.com/Arthur151/ROMP/blob/2a2ce8cf7a71372783a4969d22ccfb587fafb495/romp/lib/dataset/image_base.py#L411) and [smpl calling](https://github.com/Arthur151/ROMP/blob/b410901788586ec1776e688e1e3275f84e904d6d/romp/lib/dataset/image_base.py#L490) are fixed. Sorry for missing that issue.

You're welcome.

I have one more question: Since we're going to do pelvis keypoints alignment before evaluation anyway, why don't we directly align the pelvis keypoints to begin with, instead of root joint alignment?

**Comment by Arthur151** [comment]
You might notice that in different evaluation, we have to align to different root. Because different evaluation benchmarks have different root joint. They may share the same name (Pelvis), but they are really at different position.
To meet the pelvis defination of most in-the-wild 2D pose datasets, I choose the current root joint for alignment. It may not be the perfect choice, but I think it is obviously better than the original smpl pelvis.

**Comment by ZhengdiYu** [comment]
> You might notice that in different evaluation, we have to align to different root. Because different evaluation benchmarks have different root joint. They may share the same name (Pelvis), but they are really at different position. To meet the pelvis defination of most in-the-wild 2D pose datasets during training, I choose the current root joint for alignment. It may not be the perfect choice, but I think it is obviously better than the original smpl pelvis.

Great! Thanks! And I have another question about your result_parser:

https://github.com/Arthur151/ROMP/blob/20d440f0571643b49429ba931ed93780e7f55a41/romp/lib/maps_utils/result_parser.py#L44-L67

As I understand, **if len(batch_ids)==0**, that means there are **no matched** results. But why do you set batch_ids, flat_inds to 0, 1 if there are no results matched? I think this would make **outputs['detection_flag'] permanently True** because len(batch_dis) will at least be 1.

This means that If no person was detected, we will have a parameter sampled from batch 0, flat_inds 1 to calculate loss with batch0, person0, and no matter there is person detected or not, the param_loss and keypoints_loss will always be calculated as outputs['detection_flag'] is always True.  which I think doesn't make any sense.

Am I missing something? Could you tell me what is this for?

**Comment by Arthur151** [comment]
1. I set it to detect at least one subject for training. ROMP is trained on multiple GPUs. Pytorch achieve this via dividing the data and gathering them back. It requires the gathered dict data have the same keys for normal concatenation. Therefore, I set it to detect at least one subject to make this pipeline work.
2. I don't think it would make much differences. 
3. Please refer to 1.
4. It is developed for stable training. I write the code to make it adapt/stable to more cases.

**Comment by ZhengdiYu** [comment]
> 1. I set it to detect at least one subject for training. ROMP is trained on multiple GPUs. Pytorch achieve this via dividing the data and gathering them back. It requires the gathered dict data have the same keys for normal concatenation. Therefore, I set it to detect at least one subject to make this pipeline work.
> 2. I don't think it would make much differences.
> 3. Please refer to 1.
> 4. It is developed for stable training. I write the code to make it adapt/stable to more cases.

Thanks for your prompt reply: 

About 1, 3:  Thanks, this makes sense. But the problem still exists: 

Why don't you use corresponding flat_inds of batch 0 and person 0 to sample from param_map instead of using always (torch.ones(1)*self.map_size**2/2.)? Won't this wrong position information affect training (if the actual flat_inds is actually far from the sampling position)? This is essentially sampling parameters from where it shouldn't be.

Also, this operation is in conflict with the occasion where there are person detected:
1. **If we have detected/matched at least one person, let's say a person at batch_ids:A , person_ids:B, flat_inds:C**, we would use its GT position **C** to sample params from params_map of batch **A**(pred_param_maps[A, C]). And then compute loss between it and the GT param/pose of **B** person at batch **A**(GT_params[A, B]). This is obviously using its corresponding flat_inds to sample parameter.


Why don't you keep it in the same protocol to use GT position for sampling instead of using a meaning less position flat_inds=(torch.ones(1)*self.map_size**2/2.)?

***************
About 2: Does this mean that the camera map is very easy to learn? Even if we use a wrong projection at first, all the pj_2d will be shifted from what they should be. It will be adjust to adapt the new alignment very quickly.

**Comment by Arthur151** [comment]
Thanks for your suggestion about directly using flat_inds. I will try it later. 
The case that ROMP cannot detect a single person in the whole batch is pretty rare. It may not happen during normal training. But your suggestion makes sense. Thanks!

**Comment by Arthur151** [comment]
@ZhengdiYu 
B.T.W., I mentioned your contributions to ROMP as [this](https://github.com/Arthur151/ROMP/blob/master/README.md#contributor). Is this OK?

**Comment by ZhengdiYu** [comment]
> @ZhengdiYu B.T.W., I mentioned your contributions to ROMP as [this](https://github.com/Arthur151/ROMP/blob/master/README.md#contributor). Is this OK?

Thank you for your compliments. What I've done is just trivial compared to you and other contributors. I'm just reading code and asking question all the time.

**Comment by ZhengdiYu** [comment]
I'm new to this area, so I have more questions than others. Hope you don't mind. Thank you for your help all the time. And here comes another one about **coordinate system**, :

Q1. Why do we need alignment like smpl_root_mesh_alignment and sometime don't? If we set it to False, I think we're essentially learning the real 3D position in camera coordinate system, instead of root_relative position. In this case, I think we don't even need to predict a weak camera parameter, we only need the camera intrincics to convert to u, v coordinate. (The same goes for root-relative 3D pose).

Why am I asking this?: Now if I want to directly put those 3D meshes in MeshLab for visualization, if smpl_root_mesh_alignment is True, thus predicting the root_relative 3D coordinates, Is there a way to put them into correct position in 3D space? 

Your visualization seems to achieve this. So just now I have looked into your visualization code. You seem to convert weak camera parameter to perspective camera parameter to convert to their original 3D position, so actually we can also get their relative position in 3D space, even if we don't have GT root information. Am I understanding correctly?

************
I think current evaluation metrics in this area is not really fully considerable and reasonable for multi-person evaluation:

Q2.1 When it comes to multi-person **evaluation**, why don't we need to recover all the person to its real 3D position and put them in a common space to perform evaluation for multi-person at once, instead **align and evaluate them separately like single-person** (each person is aligned by their own pelvis and evaluate with their corresponding GT)? I think this kind of evaluation doesn't take into account the **relative position information**. The multi person could even be in random position in the space but still have good quantitative results as they're all aligned to their own GT anyway.

Q2.2  In regard to the evaluation, how did you deal with the case of **missing person**? I think now the quantitative results is only calculated for the successful detection case. There might be a method missing a lot of person but still have better quantitative results.
************
Q3. Btw, I suddenly noticed that in our previous discussion, when you have spent one night to verify 'loading pre-trained backbone or not'. **Your MPJPE in training loss seems strange**, it's too small compared to your previous log, and his and my log:
> @ZhengdiYu Hi, I have tried last night. Till now, the log is similar to yours. [V1_hrnet_nopretrain_check_h36m,mpiinf,coco,mpii,lsp,muco,crowdpose_g0,1,2,3.log](https://github.com/Arthur151/ROMP/files/8028792/V1_hrnet_nopretrain_check_h36m.mpiinf.coco.mpii.lsp.muco.crowdpose_g0.1.2.3.log) You are right. I might have load the pre-trained backbone before. Sorry for the mistake. Thanks a lot for pointing it out. I have found the reason that occurs NaN loss. It is caused by the pkp2d loss. I will try to fix this in next update.

**Comment by Arthur151** [comment]
About Q1, please note that our input is random internet images without camera parameters. This un-calibrated setting makes us to use weak-perspective camera model. But recently, some efforts are made to use perspective camera, like SPEC. 
About Q2, maybe our new work BEV can solve this problem to some extend. https://arxiv.org/abs/2112.08274
Q3. That is my log, it just likes what it looks like.

**Comment by ZhengdiYu** [comment]
About Q1,

1. Yes it is, predicting camera parameters can deal with un-calibrated camera. But I was just trying to point out that if we directly learn un-aligned mesh/kp3d. This will give us the capability to put them into correct relative position rather than a set of pelvis-centered person mesh like the image I presented.
2. How did you convert your mesh to camera coordinate system? Did you convert the weak-perspective camera to perspective camera? 
3. Why is your ROMP_HRNet_32.pkl still produces pelvis aligned mesh even if it's trained with smpl_mesh_root_align=False?

About Q3,

Yes it's your log. I was just wondering that why your training MPJPE(47, 48) is nearly 1/3 of validation MPJPE(140, 150). In your previous log, his log, and my log. This should be 1:1 (e.g. 90:95), not 1:3. Did you use a different loss calculation?

**Comment by Arthur151** [comment]
Oh, sorry, I haven't figured out the reason. I edit the code everyday. I can't remember which one causes this difference.

**Comment by ZhengdiYu** [comment]
> 1. I choose to decouple the 3D translation and 3D pose estimation and learn them individually.
> 2. Meshes are placed in 3D coordinate via predicted cam parameters
> 3. I don't get what your point?
> 
> Oh, sorry, I haven't figured out the reason. I edit the code everyday. I can't remember which one causes this difference.


Sorry for my late response:

1. What do you mean by "decouple the 3D translation and 3D pose estimation and learn them individually."? Do you mean MPJPE/PAMPJPE loss and Param Loss? Or do you mean camera parameter and MPJPE/PAMJPE loss.
2. I think you are mentioning this part, right?: https://github.com/Arthur151/ROMP/blob/1b1c37322f7096da5f544b11a1e1c1c13bf6a259/romp/lib/visualization/vedo_visualizer.py#L77
3. I just wonder that why is all the saved output meshes are pelvis aligned instead of separete in the space. I used to think that if I set smpl_mesh_root_align=False, the meshes will not be merged(algined/put) together like the image I presented, but I found that even smpl_mesh_root_align=False, they are still merged together like the image. Is it a feature of SMPL? 

For example, if we have two GT person annotations in the image, namely θ1，β1 and θ2，β2, if we put them into the SMPL layer and output two meshes without any alignment operation. Will they be in correct relative 3D position or simply put together around pelvis (or root) ?

关于问题三，可能没有说的太清楚， 用中文再説一遍哈： 

对于这方面暂时不是很懂，还在学习，多谢解答！

简单来说：             
如上图所示，**为什么test过程中保存的mesh，都是这样以臀部为中心（0，0，0）的**，而不是分散在空间中有着相互位置关系的？我本以为这个是设置了smpl_mesh_root_align的原因，但是发现设为False的时候一样也是这样粘在一起的，这是SMPL的特性吗？ 举个例子：比如说，现在有两组theta和beta，在只有theta，beta的情况下，直接输入到SMPL layer不做任何align操作，也会这样挨在一起吗？然后必须要有trans参数才能把他们放到正确相对位置的空间吗？

我记得H36M的θ和β，产生出来的mesh的root并不是0吧？请问您用的H36M的annotation是怎么得到的？您是将所有数据集全部都处理成theta和beta直接就能得出臀部为中心的mesh了吗？

--------------------
By the way:
我现在就是对于mesh相对位置关系不是很理解，我主要在想：在smpl_mesh_root_algin=True的时候很好理解，所有mesh都是root对齐的，用camera参数就能自由映射。但是，在smpl_mesh_root_algin=False的情况下，目前代码中没有用到transl参数，如果不同的数据集，有的theta，beta输进去直接得到的mesh就是root（臀部）为0的mesh，某些其他数据集得到的mesh，root又不为0，没有经过对其，那么我们学到的theta到底是啥样的呢？到时候产出的mesh会以臀部为中心吗？对于2D keypoints又会怎么影响呢？ 

**举个极端点的例子**，假设同一张图片分别出现在两个不同的数据集中，这两个数据集的的smpl参数annotation法则不同，一个用θ和β直接产出的mesh全都是root为0的，另一个数据集的规则是有transl参数，去掉transl之后直接产生meshes的root不为0，所以第一个数据集中用GT产出的mesh全是挨在一起的， 第二个就不会挨在一起。这种情况下，假设整个dataset就只有这两张相同的图片+两组不同的annotation，如果让网络去对着这两帧过拟合，这时候其中一张图产出的mesh全是臀部为中心，另一个则不是，但是由于是同一张图，他们的GT 2d keypoints却是一致的，那我们的camera参数岂不是产生歧义了？或者说假设两张图片很像，他们上面的GT 2D keypoints也很像，但是他们的annotation法则不同，怎么办？**应该要把所有数据集的θ和β处理成直接拿过来就能产出已经对齐的mesh吧？**

**Comment by Arthur151** [comment]
1. Supervising the root-relative pose can learn pose independently. In contrast, supervising the  un-aligned mesh/kp3d will focus the model to learn the 3D translation and 3D pose simultanousely, which couples two factors.
2. Yes.
3. Yes, theta controls the pose only while beta controls the shape only. None of them can effect the root position. Therefore, all smpl meshes are always root aligned. 
I didn't use the trans of h36m dataset.

**Comment by ZhengdiYu** [comment]
> 1. Supervising the root-relative pose can learn pose independently. In contrast, supervising the  un-aligned mesh/kp3d will focus the model to learn the 3D translation and 3D pose simultanousely, which couples two factors.
> 2. Yes.
> 3. Yes, theta controls the pose only while beta controls the shape only. None of them can effect the root position. Therefore, all smpl meshes are always root aligned.
>    I didn't use the trans of h36m dataset.
> 
> I suggest that you might need to go deep into the smpl model, like understanding the code. Then you would not have such confusions.

Thanks for your quick apply. Thanks for your suggestion, I will look into it tomorrow. and by the way, last thing to confirm，did you preprocess the h36m’ theta and beta to be root aligned？I think，without trans， it‘s not root aligned originally and in the world coordinate system.

So I guess you **only transform theta and beta to camera coordinate system，and use them directly without trans，**right？
