### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ROMP/model_data/parameters/SMPL_NEUTRAL.pkl'

### ISSUE THREAD

**Issue by mkhoshle** [Arthur151/ROMP#163]
I am running the following command: "python -m romp.lib.dataset.pw3d" and I am getting the following error:
```
Confidence: 0.2
configs_yml: /z/home/mahzad-khosh/ROMP/configs/v1.yml
model_version: 1
test_projection_part: False
Initialized dataset
Traceback (most recent call last):
  File "/z/home/mahzad-khosh/handpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/z/home/mahzad-khosh/handpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/z/home/mahzad-khosh/ROMP/romp/lib/dataset/pw3d.py", line 419, in <module>
    test_dataset(dataset,with_3d=True,with_smpl=True)
  File "/z/home/mahzad-khosh/ROMP/romp/lib/dataset/image_base.py", line 488, in test_dataset
    visualizer = Visualizer(resolution = (512,512,3), result_img_dir=save_dir)
  File "/z/home/mahzad-khosh/ROMP/romp/lib/models/../utils/../visualization/visualization.py", line 30, in __init__
    self.smpl_face = torch.from_numpy(pickle.load(open(os.path.join(args().smpl_model_path,'SMPL_NEUTRAL.pkl'),'rb'), \
FileNotFoundError: [Errno 2] No such file or directory: '/z/home/mahzad-khosh/ROMP/model_data/parameters/SMPL_NEUTRAL.pkl'
```
Where am I supposed to get the 'SMPL_NEUTRAL.pkl' file?

**Comment by mkhoshle** [comment]
I close this issue as I was able to get the file from here:
wget https://github.com/Arthur151/ROMP/releases/download/v1.1/model_data.zip
