### ISSUE TITLE
No LSPet_ver01.json available

### ISSUE THREAD

**Issue by boreshkinai** [Arthur151/ROMP#181]
To reproduce: `python -m romp.lib.dataset.lsp`

Stack trace:

root@d6613ad97b7d:/workspace/pose-estimation/ROMP# python -m romp.lib.dataset.lsp                                      
yaml_timestamp  /workspace/pose-estimation/ROMP/active_configs/active_context_2022-03-30_14_49_41.yaml                  Confidence: 0.2                                                                                                         
Traceback (most recent call last):                                                                                        
    File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
                                                "__main__", mod_spec)                                                                                                 
    File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
                                                           exec(code, run_globals)                                                                                               
    File "/workspace/pose-estimation/ROMP/romp/lib/dataset/lsp.py", line 90, in <module>
                                      dataset=LSP(regress_smpl=True)                                                                                        
   File "/workspace/pose-estimation/ROMP/romp/lib/dataset/lsp.py", line 11, in __init__ 
                                     self.load_data()                                                                                                      
   File "/workspace/pose-estimation/ROMP/romp/lib/dataset/lsp.py", line 38, in load_data
                                     self.load_eft_annots(os.path.join(config.project_dir, 'data/eft_fit/LSPet_ver01.json'))                               
   File "/workspace/pose-estimation/ROMP/romp/lib/dataset/lsp.py", line 44, in load_eft_annots
                               annots = json.load(open(annot_file_path,'r'))['data']                                                               
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/pose-estimation/ROMP/data/eft_fit/LSPet_ver01.json'

**Comment by boreshkinai** [comment]
This was due to misplaced eft_annots.npz

**Comment by ArtiX-GP** [comment]
Hi, @boreshkinai 
What path is? `./data/eft_fit/eft_annots.npz` ?
