### ISSUE TITLE
[simple-romp] pip package 'black' not installed

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#190]
I tested an clean install of `simple-romp`:
```
(base) PS C:\Users\Vivien> conda create -n sromp
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\tools\miniconda3\envs\sromp



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate sromp
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS C:\Users\Vivien> conda activate sromp
(sromp) PS C:\Users\Vivien> conda list
# packages in environment at C:\tools\miniconda3\envs\sromp:
#
# Name                    Version                   Build  Channel
(sromp) PS C:\Users\Vivien> conda install pip
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\tools\miniconda3\envs\sromp

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.3.29  |       haa95532_0         122 KB
    openssl-1.1.1n             |       h2bbff1b_0         4.8 MB
    python-3.9.11              |       h6244533_2        17.1 MB
    sqlite-3.38.2              |       h2bbff1b_0         807 KB
    tzdata-2022a               |       hda174b7_0         109 KB
    ------------------------------------------------------------
                                           Total:        22.9 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2022.3.29-haa95532_0
  certifi            pkgs/main/win-64::certifi-2021.10.8-py39haa95532_2
  openssl            pkgs/main/win-64::openssl-1.1.1n-h2bbff1b_0
  pip                pkgs/main/win-64::pip-21.2.4-py39haa95532_0
  python             pkgs/main/win-64::python-3.9.11-h6244533_2
  setuptools         pkgs/main/win-64::setuptools-58.0.4-py39haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.38.2-h2bbff1b_0
  tzdata             pkgs/main/noarch::tzdata-2022a-hda174b7_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py39haa95532_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
sqlite-3.38.2        | 807 KB    | ################################################################################################################################################################################################# | 100%
python-3.9.11        | 17.1 MB   | ################################################################################################################################################################################################# | 100%
tzdata-2022a         | 109 KB    | ################################################################################################################################################################################################# | 100%
openssl-1.1.1n       | 4.8 MB    | ################################################################################################################################################################################################# | 100%
ca-certificates-2022 | 122 KB    | ################################################################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(sromp) PS C:\Users\Vivien> pip install simple-romp
Collecting simple-romp
  Downloading simple_romp-0.0.3.tar.gz (74 kB)
     |████████████████████████████████| 74 kB 579 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting torch
  Downloading torch-1.11.0-cp39-cp39-win_amd64.whl (157.9 MB)
     |████████████████████████████████| 157.9 MB 2.1 kB/s
Collecting opencv-python
  Downloading opencv_python-4.5.5.64-cp36-abi3-win_amd64.whl (35.4 MB)
     |████████████████████████████████| 35.4 MB 87 kB/s
Collecting numpy>=1.17.3
  Using cached numpy-1.22.3-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Building wheels for collected packages: simple-romp
  Building wheel for simple-romp (PEP 517) ... done
  Created wheel for simple-romp: filename=simple_romp-0.0.3-cp39-cp39-win_amd64.whl size=108795 sha256=de8f5c45a99003ccfa9802b54edcde0bdb444397495829e7c9b37a51f52392fd
  Stored in directory: e:\appdata\local\pip\cache\wheels\4b\ed\ce\b451ccf503fb9a5d420ed28b8b8ae0b4c729ed4536e01fda97
Successfully built simple-romp
Installing collected packages: typing-extensions, numpy, torch, opencv-python, simple-romp
Successfully installed numpy-1.22.3 opencv-python-4.5.5.64 simple-romp-0.0.3 torch-1.11.0 typing-extensions-4.1.1
(sromp) PS C:\Users\Vivien> conda list
# packages in environment at C:\tools\miniconda3\envs\sromp:
#
# Name                    Version                   Build  Channel
ca-certificates           2022.3.29            haa95532_0
certifi                   2021.10.8        py39haa95532_2
numpy                     1.22.3                   pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
openssl                   1.1.1n               h2bbff1b_0
pip                       21.2.4           py39haa95532_0
python                    3.9.11               h6244533_2
setuptools                58.0.4           py39haa95532_0
simple-romp               0.0.3                    pypi_0    pypi
sqlite                    3.38.2               h2bbff1b_0
torch                     1.11.0                   pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
tzdata                    2022a                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
```
and tested it by:
```
(sromp) PS C:\Users\Vivien> romp --mode=webcam --show
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\sromp\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\tools\miniconda3\envs\sromp\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tools\miniconda3\envs\sromp\Scripts\romp.exe\__main__.py", line 4, in <module>
  File "C:\tools\miniconda3\envs\sromp\lib\site-packages\romp\__init__.py", line 1, in <module>
    from .main import ROMP, romp_settings
  File "C:\tools\miniconda3\envs\sromp\lib\site-packages\romp\main.py", line 10, in <module>
    from .post_parser import SMPL_parser, body_mesh_projection2image, parsing_outputs
  File "C:\tools\miniconda3\envs\sromp\lib\site-packages\romp\post_parser.py", line 6, in <module>
    from .utils import rot6D_to_angular, batch_orth_proj
  File "C:\tools\miniconda3\envs\sromp\lib\site-packages\romp\utils.py", line 3, in <module>
    from black import out
ModuleNotFoundError: No module named 'black'
```
As you can clearly see, there is no [`black`](https://pypi.org/project/black) package installed.
An workaround is to install the `black` package in an manual way.
For example also by `pip`:
```
(sromp) PS C:\Users\Vivien> pip install black
Collecting black
  Using cached black-22.3.0-cp39-cp39-win_amd64.whl (1.1 MB)
Collecting click>=8.0.0
  Using cached click-8.1.2-py3-none-any.whl (96 kB)
Collecting platformdirs>=2
  Using cached platformdirs-2.5.1-py3-none-any.whl (14 kB)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\tools\miniconda3\envs\sromp\lib\site-packages (from black) (4.1.1)
Collecting pathspec>=0.9.0
  Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: colorama, tomli, platformdirs, pathspec, mypy-extensions, click, black
Successfully installed black-22.3.0 click-8.1.2 colorama-0.4.4 mypy-extensions-0.4.3 pathspec-0.9.0 platformdirs-2.5.1 tomli-2.0.1
```
But it should be already installed, because: https://github.com/Arthur151/ROMP/blob/2db91146ad3d880a9542d6f78d688cc1dcc980cc/simple_romp/setup.py#L22

Is this an bug?
Any ideas to fix it?

Also it seems to me, that the `black` package is not required just for testing.
So how about changing the `import`s accordingly?

**Comment by Arthur151** [comment]
Hi, Vivien Richter,
Long time no see! 
Thanks for the bug report! 
Yes, I notice this bug (lacking 'black') when testing the installation of simple-romp on Mac / Windows. So I add it to the requires. It is pretty weird.

Sure, the reliance of black has been removed in V0.0.3. Sorry that I forget to delete it. My bad. 

Thanks again, my friend!

**Comment by vivi90** [comment]
@Arthur151 No problem :)
Please deploy the fixed version:
```
(sromp) PS C:\Users\Vivien> pip install simple-romp
Collecting simple-romp
  Using cached simple_romp-0.0.3-cp39-cp39-win_amd64.whl
Collecting torch
  Using cached torch-1.11.0-cp39-cp39-win_amd64.whl (157.9 MB)
Collecting opencv-python
  Using cached opencv_python-4.5.5.64-cp36-abi3-win_amd64.whl (35.4 MB)
Collecting numpy>=1.19.3
  Using cached numpy-1.22.3-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, numpy, torch, opencv-python, simple-romp
Successfully installed numpy-1.22.3 opencv-python-4.5.5.64 simple-romp-0.0.3 torch-1.11.0 typing-extensions-4.1.1
```
There is still the old one.
