### ISSUE TITLE
smpl does not exist

### ISSUE THREAD

**Issue by mkhoshle** [Arthur151/ROMP#226]
Hi,

I am running the code in training mode and after two epochs I get the following error:
```
Traceback (most recent call last):
  File "/z/home/mahzad-khosh/env/romp/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/z/home/mahzad-khosh/env/romp/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/z/home/mahzad-khosh/ROMP/romp/train.py", line 153, in <module>
    main()
  File "/z/home/mahzad-khosh/ROMP/romp/train.py", line 150, in main
    trainer.train()
  File "/z/home/mahzad-khosh/ROMP/romp/train.py", line 35, in train
    self.train_epoch(epoch)
  File "/z/home/mahzad-khosh/ROMP/romp/train.py", line 103, in train_epoch
    self.validation(epoch)
  File "/z/home/mahzad-khosh/ROMP/romp/train.py", line 118, in validation
    MPJPE, PA_MPJPE, eval_results = val_result(self,loader_val=val_loader, evaluation=False)
  File "/z/home/mahzad-khosh/env/romp/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/z/home/mahzad-khosh/ROMP/romp/eval.py", line 68, in val_result
    MPJPE_result, PA_MPJPE_result, eval_matrix = print_results(ED.copy())
  File "/z/home/mahzad-khosh/ROMP/romp/eval.py", line 101, in print_results
    eval_matrix['{}-PVE'.format(ds_name)] = np.mean(compute_error_verts(target_theta=torch.cat(ED['PVE'][ds_name]['target_theta'],0), \
  File "/z/home/mahzad-khosh/ROMP/romp/lib/models/../utils/../evaluation/evaluation_matrix.py", line 20, in compute_error_verts
    target_verts = get_verts(target_theta, smpl_path)    #os.path.join(config.model_dir,'smpl_models','smpl')
  File "/z/home/mahzad-khosh/ROMP/romp/lib/models/../utils/../evaluation/evaluation_matrix.py", line 30, in get_verts
    smpl = SMPL(smpl_path,batch_size=1).to(device)
  File "/z/home/mahzad-khosh/env/romp/lib/python3.8/site-packages/smplx/body_models.py", line 133, in __init__
    assert osp.exists(smpl_path), 'Path {} does not exist!'.format(
AssertionError: Path /z/home/mahzad-khosh/ROMP/model_data/parameters/smpl does not exist!
```
Can you please help me figure out why this might be the case? 
I do have the model_data/parameters and it contains the following files:
```
cube_parts.npy  J_regressor_extra.npy  lmk_embedding_intraface_to_flame.pkl  SMPL_MALE.pkl  SMPL_NEUTRAL.pkl  test_smpl.py
gmm_08.pkl      J_regressor_h36m.npy   SMPL_FEMALE.pkl                       smpl_male.vtk  smpl_vt_ft.npz
```

**Comment by Arthur151** [comment]
Sorry for the late reply!
I see the bug. It is caused by the different path settings of smpl model in smplx.
To fix it, you can simply create a folder 
/z/home/mahzad-khosh/ROMP/model_data/parameters/smpl
and paste the SMPL model files (SMPL_MALE.pkl,SMPL_NEUTRAL.pkl,SMPL_FEMALE.pkl ) into it, like /z/home/mahzad-khosh/ROMP/model_data/parameters/smpl/SMPL_NEUTRAL.pkl
