### ISSUE TITLE
BEV's evaluation encoutered error on AGORA dataset.

### ISSUE THREAD

**Issue by Rabbit314271** [Arthur151/ROMP#295]
Hi, Doc. Sun. It's me again. :-). This time when I run BEV's test on AGORA, the BEV's module somehow encountered 'no attribute' error. More specificly, the `setting` of module `BEV` had no attribute called `show_items`. Detailed infomation shows as below when I run eval_AGORA.py.

`Using BEV.
Threshold for positive center detection: 0.15
Traceback (most recent call last):
  File "/home/gpu/content/ROMP/simple_romp/evaluation/eval_AGORA.py", line 125, in <module>
    get_results_on_AGORA(set_name)
  File "/home/gpu/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/gpu/content/ROMP/simple_romp/evaluation/eval_AGORA.py", line 110, in get_results_on_AGORA
    model = BEV(default_eval_settings)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bev/main.py", line 94, in __init__
    self._initilization_()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bev/main.py", line 111, in _initilization_
    self.visualize_items = self.settings.show_items.split(',')
AttributeError: 'Namespace' object has no attribute 'show_items'
`

Hope for your answer. 👍

**Comment by Arthur151** [comment]
Hi, @Rabbit314271,

Thanks for reporting the bug again. 

I have submited a commit to fix this bug. 
Check this:
https://github.com/Arthur151/ROMP/commit/376baf788fdb67f36d6b11dde1dcbdd388c11072
Please update the code.

**Comment by Rabbit314271** [comment]
Thank you very much for fixing the problem so quickly.
By the way, in the function `save_agora_predictions_v6(line 79)` of eval_AGORA.py, the input dict `outputs` should contain keys like `body_pose(to be used in line 94& line 97)` or `'global_orient' (to be used in line 96).` However, when I print all the keys of the input dict `outputs`, it only contains :

`params_pred,
pred_batch_ids,
center_confs,
cam,
smpl_thetas,
smpl_betas,
cam_trans,
verts,
joints,
pj2d_org,
`

As a result, it will report a `keyerror `:

`Traceback (most recent call last):
  File "/home/gpu/content/ROMP1/simple_romp/evaluation/eval_AGORA.py", line 128, in <module>
    get_results_on_AGORA(set_name)
  File "/home/gpu/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/gpu/content/ROMP1/simple_romp/evaluation/eval_AGORA.py", line 124, in get_results_on_AGORA
    save_agora_predictions_v6(image_path, outputs, prediction_save_dir)
  File "/home/gpu/content/ROMP1/simple_romp/evaluation/eval_AGORA.py", line 96, in save_agora_predictions_v6
    for ind in range(len(outputs['body_pose'])):
KeyError: 'body_pose'
`

Hoping for your answer. :-)

**Comment by Arthur151** [comment]
Thanks for the bug reporting. 
Sorry I don't have the resource to test the code now. The bug is supposed to be fixed in last commit:
https://github.com/Arthur151/ROMP/commit/a316fc475877677f3506b24628b8690ff21307be

**Comment by Rabbit314271** [comment]
OK! Now, everything functions well! Thank you very much for all these effort!

**Comment by Arthur151** [comment]
@Rabbit314271 
Thank you for reporting these bugs. 
Have a nice day. 
Best
