### ISSUE TITLE
Evaluation on CMU Panoptic Error

### ISSUE THREAD

**Issue by RedOrient** [Arthur151/ROMP#312]
大佬您好，我在进行Evaluation on CMU Panoptic的时候遇到了问题，描述如下：

这是我的config
[eval_cmu_panoptic.yml.txt](https://github.com/Arthur151/ROMP/files/9142343/eval_cmu_panoptic.yml.txt)

这是我的数据集
![image](https://user-images.githubusercontent.com/31726551/179784495-9bb6fcd3-4e32-4891-a4b9-9acd1e624e8f.png)
![image](https://user-images.githubusercontent.com/31726551/179784575-b88a31af-4c01-431f-92fc-500901f8c4d6.png)

```
INFO:root:using fine_tune model: E:/Git-Project/ROMP/checkpoints/hrnet_cm64_V1_hrnet_on_gpu0,1,2,3_val/0_64.8211_44.4677_hrnet_cm64_V1_hrnet.pkl
INFO:root:copy param _result_parser.params_map_parser.smpl_model.betas failed, mismatched
INFO:root:missing parameters of layers:[]
INFO:root:Train all layers, except: ['_result_parser.params_map_parser.smpl_model.betas']
Initialization finished!
INFO:root:gathering datasets
Confidence: 0.2
Traceback (most recent call last):
  File "D:\Software\AnacondaP\Install\envs\ROMP\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\AnacondaP\Install\envs\ROMP\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Git-Project\ROMP\romp1\romp\test.py", line 204, in <module>
    main()
  File "E:\Git-Project\ROMP\romp1\romp\test.py", line 195, in main
    demo.test_cmu_panoptic()
  File "E:\Git-Project\ROMP\romp1\romp\test.py", line 49, in test_cmu_panoptic
    data_loader = self._create_single_data_loader(dataset='cmup', train_flag=False, split='test')
  File "E:\Git-Project\ROMP\romp1\romp\base.py", line 140, in _create_single_data_loader
    datasets = SingleDataset(**kwargs)
  File "E:\Git-Project\ROMP\romp1\romp\lib\models\..\utils\..\dataset\mixed_dataset.py", line 86, in __init__
    self.dataset = dataset_dict[dataset](**kwargs)
  File "E:\Git-Project\ROMP\romp1\romp\lib\models\..\utils\..\dataset\cmu_panoptic_eval.py", line 14, in __init__
    self.load_annots()
  File "E:\Git-Project\ROMP\romp1\romp\lib\models\..\utils\..\dataset\cmu_panoptic_eval.py", line 30, in load_annots
    img_infos = pickle.load(f)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

麻烦看下是什么原因~

**Comment by Arthur151** [comment]
Please unzip the panoptic_annot.zip, which contains  four pkl files we requires

**Comment by jhkim0759** [comment]
How can I get the panoptic_annot.zip file? I can't find from the google drive

**Comment by Arthur151** [comment]
@jhkim0759 
[https://drive.google.com/file/d/1XwiGFwSwTdwoV1aJ4A-PS45Tz1Nz2nJt/view?usp=sharing
This would be the](https://drive.google.com/file/d/1zdaCmc53367CaOOMoBwt6nn5APocX4Rv/view?usp=sharing)
