### ISSUE TITLE
ROMP_colab YAML not found

### ISSUE THREAD

**Issue by Zinia17** [Arthur151/ROMP#332]
Hi @Arthur151 
What is the meaning of following error which I encountered in google Colab? I think the yaml file is missing in the active_config directory. Please check the issue.

No configs_yml is set, set it to the default --configs_yml=configs/image.yml
yaml_timestamp  /content/ROMP/active_configs/active_context_2022-08-10_12_57_59.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/ROMP/romp/predict/image.py", line 7, in <module>
    from .base_predictor import *
  File "/content/ROMP/romp/predict/base_predictor.py", line 1, in <module>
    from ..base import *
  File "/content/ROMP/romp/base.py", line 16, in <module>
    from models import build_model
  File "/content/ROMP/romp/lib/models/__init__.py", line 6, in <module>
    from .build import build_model
  File "/content/ROMP/romp/lib/models/build.py", line 7, in <module>
    from models.romp_model import ROMP
  File "/content/ROMP/romp/lib/models/romp_model.py", line 18, in <module>
    from loss_funcs import Loss
  File "/content/ROMP/romp/lib/models/../loss_funcs/__init__.py", line 6, in <module>
    from .calc_loss import Loss
  File "/content/ROMP/romp/lib/models/../loss_funcs/calc_loss.py", line 23, in <module>
    from maps_utils.centermap import CenterMap
  File "/content/ROMP/romp/lib/models/../maps_utils/__init__.py", line 6, in <module>
    from .kp_group import HeatmapParser
  File "/content/ROMP/romp/lib/models/../maps_utils/kp_group.py", line 13, in <module>
    from munkres import Munkres
ModuleNotFoundError: No module named 'munkres'

**Comment by Arthur151** [comment]
Sorry for the late reply. 
The colab has not been mantained for a long time. Most features of ROMP/BEV could be implemented in simple-romp, which could be easily installed via pip.
https://github.com/Arthur151/ROMP/tree/master/simple_romp

**Comment by Zinia17** [comment]
Thanks for the reply.
