### ISSUE TITLE
关于temporal optimize使用的问题请教

### ISSUE THREAD

**Issue by Seeseallllll** [Arthur151/ROMP#367]
感谢您的工作，在我尝试使用temporal optimize时，出现了如下问题。
不清楚要怎么解决，还请您指教

(ROMP) ubuntu18@ubuntu18:~/deep_learning/ROMP/simple_romp$ romp --mode=video --calc_smpl --render_mesh -i='/home/ubuntu18/deep_learning/ROMP/test/video1/sample_video.mp4'  -o='/home/ubuntu18/deep_learning/ROMP/test/video1/sample_video_out.mp4' --temporal_optimize --smooth_coeff=3 --show
Using ROMP v1
Extracting the frames of input /home/ubuntu18/deep_learning/ROMP/test/video1/sample_video.mp4 to /home/ubuntu18/deep_learning/ROMP/test/video1/sample_video_frames
Traceback (most recent call last):
  File "/home/ubuntu18/anaconda3/envs/ROMP/bin/romp", line 33, in <module>
    sys.exit(load_entry_point('simple-romp==1.0.5', 'console_scripts', 'romp')())
  File "/home/ubuntu18/anaconda3/envs/ROMP/lib/python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/romp/main.py", line 191, in main
    outputs = romp(image)
  File "/home/ubuntu18/anaconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu18/anaconda3/envs/ROMP/lib/python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/romp/utils.py", line 725, in wrap_func
    result = func(*args, **kwargs)
  File "/home/ubuntu18/anaconda3/envs/ROMP/lib/python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/romp/main.py", line 164, in forward
    outputs = self.temporal_optimization(outputs, signal_ID)
  File "/home/ubuntu18/anaconda3/envs/ROMP/lib/python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/romp/main.py", line 146, in temporal_optimization
    tracked_ids = get_tracked_ids(detections, tracked_objects)
  File "/home/ubuntu18/anaconda3/envs/ROMP/lib/python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/romp/utils.py", line 281, in get_tracked_ids
    tracked_ids = [tracked_ids_out[np.argmin(np.linalg.norm(tracked_points-point[None], axis=1))] for point in org_points]
  File "/home/ubuntu18/anaconda3/envs/ROMP/lib/python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/romp/utils.py", line 281, in <listcomp>
    tracked_ids = [tracked_ids_out[np.argmin(np.linalg.norm(tracked_points-point[None], axis=1))] for point in org_points]
IndexError: index 4 is out of bounds for axis 0 with size 4

**Comment by Arthur151** [comment]
十分感谢bug report！
同时也很抱歉，目前开源的BEV的时域追踪和优化功能还很不稳定，还无法处理很复杂的tracking场景，我已经在待发表的新版本中优化了这一问题，期待可以尽快开源。

**Comment by Seeseallllll** [comment]
> 
感谢大佬！试了一下，romp的结果有点问题，不过bev可以正常使用了，NICE！

**Comment by 1309723614** [comment]
在1.0.8中遇到了这个问题，请问我是不是要降到1.0.6呢？ffmpeg换个帧率抽取问题又变成了[issues255](https://github.com/Arthur151/ROMP/issues/255)，看来部分素材不太能完美运行呢。请问作者针对这种情况有什么建议吗？
