### ISSUE TITLE
pyrender and opengl issue on VMs

### ISSUE THREAD

**Issue by alighofrani95** [Arthur151/ROMP#39]
I have to try loading the project on VM machine and this issue occurs,
my machine is UBUNTU 18.04, and 3D is enabled in VMware.
Indeed I tried with multiple pyrender and OpenGL Versions but doesn't solve it.

INFO - 2021-05-02 18:43:37,442 - base - finished build model.
Traceback (most recent call last):
  File "/root/Desktop/final/m3d/src/core/test.py", line 230, in <module>
    main()
  File "/root/Desktop/final/m3d/src/core/test.py", line 210, in main
    demo = Demo()
  File "/root/Desktop/final/m3d/src/core/test.py", line 7, in __init__
    self._prepare_modules_()
  File "/root/Desktop/final/m3d/src/core/test.py", line 15, in _prepare_modules_
    self.visualizer = Visualizer(resolution=self.vis_size, input_size=self.input_size,with_renderer=True)
  File "/root/Desktop/final/m3d/src/core/../lib/models/../utils/../maps_utils/../dataset/../dataset/../dataset/../visualization/visualization.py", line 23, in __init__
    self.renderer = get_renderer(resolution=resolution)
  File "/root/Desktop/final/m3d/src/core/../lib/models/../utils/../maps_utils/../dataset/../dataset/../dataset/../visualization/../visualization/renderer.py", line 142, in get_renderer
    renderer = Renderer(faces,resolution=resolution[:2])
  File "/root/Desktop/final/m3d/src/core/../lib/models/../utils/../maps_utils/../dataset/../dataset/../dataset/../visualization/../visualization/renderer.py", line 72, in __init__
    point_size=1.0)
  File "/usr/local/lib/python3.6/dist-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/usr/local/lib/python3.6/dist-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/usr/local/lib/python3.6/dist-packages/pyrender/platforms/egl.py", line 188, in init_context
    EGL_NO_CONTEXT, context_attributes
  File "/usr/local/lib/python3.6/dist-packages/OpenGL/platform/baseplatform.py", line 409, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 12297,
	baseOperation = eglCreateContext,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f3dba91e2f0>,
		<OpenGL._opaque.EGLConfig_pointer object at 0x7f3dba91e378>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f3dbcaabe18>,
		<OpenGL.arrays.lists.c_int_Array_7 object at 0x7f3dbcaab1e0>,
	),
	result = <OpenGL._opaque.EGLContext_pointer object at 0x7f3dba940268>
)

**Comment by Arthur151** [comment]
I have met this problem on one of three remote servers. It occurs in some times but not always. You can try to repeatly run the code. This error doesn't occur in some times.

**Comment by cvTensor** [comment]
you could reinstall cuda driver with opengl support.

**Comment by JiajunWan** [comment]
I found a solution in this [post](https://github.com/mmatl/pyrender/issues/86#issuecomment-767613647).

**Comment by Arthur151** [comment]
Does adding the  `MESA_GL_VERSION_OVERRIDE=4.1` work for you? @JiajunWan

**Comment by JiajunWan** [comment]
> Does adding the `MESA_GL_VERSION_OVERRIDE=4.1` work for you? @JiajunWan

Yeah it worked. But in my case I also need to change GL_MAX_SAMPLES  to 1 in glRenderbufferStorageMultisample() as it says in the post.
