### ISSUE TITLE
ERROR: Invalid requirement: 'tools/bpy-2.82.1'

### ISSUE THREAD

**Issue by Wanglibin14715** [Arthur151/ROMP#441]
I follow the guide trying to export .fbx in WINDOWS
https://github.com/Arthur151/ROMP/blob/master/simple_romp/doc/export.md

Everything went smoothly at first, and no error occurred until last step python tools/convert2fbx.py.

It's depressed cause I spent all day, and worse is I hadn't solved it.

I don't know why it required 'tools/bpy-2.82.1', while the guide above asking install bpy-2.91a0-cp37-cp37m-win_amd64.whl && bpy_post_install.

by the way, 
https://github.com/TylerGubala/blenderpy/releases
it asked "Install your Windows library dependencies (see [the Blender wiki](https://wiki.blender.org/wiki/Building_Blender/Windows), install all dependencies that have lib in the name for your given platform)"
I am not sure what's the necessary dependencies, it might be the cause.

Do me a favor if you see this page, thank you.

Full ERROR MESSAGE
`(romp_export) D:\Github\ROMP>python simple_romp/tools/convert2fbx.py --input=/example/input.npy --output=/example/dance.fbx --gender=female
Missing bpy, install via pip, please install bpy by yourself if failed.
Requirement already satisfied: future-fstrings in c:\users\libin.wang\.conda\envs\romp_export\lib\site-packages (1.2.0)
ERROR: Invalid requirement: 'tools/bpy-2.82.1'
Traceback (most recent call last):
  File "simple_romp/tools/convert2fbx.py", line 36, in <module>
    import bpy
ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple_romp/tools/convert2fbx.py", line 41, in <module>
    import bpy
ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。`

install bpy
`(romp_export) D:\Github\ROMP>pip install bpy-2.91a0-cp37-cp37m-win_amd64.whl && bpy_post_install
Processing d:\github\romp\bpy-2.91a0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: numpy in c:\users\libin.wang\.conda\envs\romp_export\lib\site-packages (from bpy==2.91a0) (1.21.6)
bpy is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Found Blender scripts directory at C:\Users\libin.wang\.conda\envs\romp_export\2.91
C:\Users\libin.wang\.conda\envs\romp_export\2.91 already direct child of C:\Users\libin.wang\.conda\envs\romp_export
Configuration complete, enjoy using Blender as a Python module!`

**Comment by Wanglibin14715** [comment]
Hey huys, I found the main problem is bpy is not working.
I just simply import bpy
'
>>> import bpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed:应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。
'
but when I try to reinstall bpy, it says this, same everything ok.
'(romp_export) D:\Github\ROMP>pip install bpy-2.91a0-cp37-cp37m-win_amd64.whl && bpy_post_install 
Processing d:\github\romp\bpy-2.91a0-cp37-cp37m-win_amd64.whl 
Requirement already satisfied: numpy in c:\users\libin.wang\.conda\envs\romp_export\lib\site-packages (from bpy==2.91a0) (1.21.6) bpy is already installed with the same version as the provided wheel. 
exit()Use --force-reinstall to force an installation of the wheel. Found Blender scripts directory at C:\Users\libin.wang\.conda\envs\romp_export\2.91 C:\Users\libin.wang\.conda\envs\romp_export\2.91 already direct child of C:\Users\libin.wang\.conda\envs\romp_export Configuration complete, enjoy using Blender as a Python module!'

**Comment by WingkitChou** [comment]
Did you slove it?

**Comment by HuaTu22934** [comment]
Came across same problem and same error message. Did you solve it?
