### ISSUE TITLE
Cannot evaluate on 3DPW

### ISSUE THREAD

**Issue by kaufManu** [Arthur151/ROMP#442]
Hi,

I'm trying to run

```
python -m romp.test --configs_yml=configs/eval_3dpw_test.yml
```

but it fails at this line:

```
INFO:root:3DPW dataset test split total 24423 samples, loading mode vibe, containing 24 video sequence.
Traceback (most recent call last):
  File "miniconda3/envs/ROMP/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "miniconda3/envs/ROMP/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "ROMP/romp/test.py", line 204, in <module>
    main()
  File "ROMP/romp/test.py", line 201, in main
    demo.test_eval()
  File "ROMP/romp/test.py", line 27, in test_eval
    MPJPE, PA_MPJPE, eval_results = val_result(self,loader_val=data_loader, evaluation=True)
  File "miniconda3/envs/ROMP/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "code/ROMP/romp/eval.py", line 103, in val_result
    outputs = self.network_forward(eval_model, meta_data, self.eval_cfg)
  File "ROMP/romp/base.py", line 121, in network_forward
    outputs = model(meta_data, **self.train_cfg)
AttributeError: 'Demo' object has no attribute 'train_cfg'
```

This first failed silently as the line is in a `try`-`except` block that executes `continue` if there's an error. I found other issues on Github that report that the evaluation is broken on the newest release, but I didn't unterstand the comments of those threads. Is there a quick way to fix this?

**Comment by lyk412** [comment]
Hi! I also met this problem. Do you fix it for evaluation on 3DPW?

**Comment by lyk412** [comment]
> Hi,
> 
> I'm trying to run
> 
> ```
> python -m romp.test --configs_yml=configs/eval_3dpw_test.yml
> ```
> 
> but it fails at this line:
> 
> ```
> INFO:root:3DPW dataset test split total 24423 samples, loading mode vibe, containing 24 video sequence.
> Traceback (most recent call last):
>   File "miniconda3/envs/ROMP/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "miniconda3/envs/ROMP/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "ROMP/romp/test.py", line 204, in <module>
>     main()
>   File "ROMP/romp/test.py", line 201, in main
>     demo.test_eval()
>   File "ROMP/romp/test.py", line 27, in test_eval
>     MPJPE, PA_MPJPE, eval_results = val_result(self,loader_val=data_loader, evaluation=True)
>   File "miniconda3/envs/ROMP/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "code/ROMP/romp/eval.py", line 103, in val_result
>     outputs = self.network_forward(eval_model, meta_data, self.eval_cfg)
>   File "ROMP/romp/base.py", line 121, in network_forward
>     outputs = model(meta_data, **self.train_cfg)
> AttributeError: 'Demo' object has no attribute 'train_cfg'
> ```
> 
> This first failed silently as the line is in a `try`-`except` block that executes `continue` if there's an error. I found other issues on Github that report that the evaluation is broken on the newest release, but I didn't unterstand the comments of those threads. Is there a quick way to fix this?

Hi, I also met this problem when evaluation. Do you fix it?
