### ISSUE TITLE
Missing deform_conv Modules

### ISSUE THREAD

**Issue by TonyzBi** [Arthur151/ROMP#456]
Thanks for your great jobs, but when i was trying  to  run trace2, I got following error, could you help to find out "which step about installation I was missing ? ".

```
~/ROMP$ CUDA_VISIBLE_DEVICES=0 trace2 -i simple_romp/trace_demo --subject_num=1
alt_cuda_corr is not compiled
Traceback (most recent call last):
  File "/home/bihai/anaconda3/envs/PY38/bin/trace2", line 33, in <module>
    sys.exit(load_entry_point('simple-romp==2.0.2', 'console_scripts', 'trace2')())
  File "/home/bihai/anaconda3/envs/PY38/bin/trace2", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/bihai/anaconda3/envs/PY38/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/bihai/anaconda3/envs/PY38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bihai/anaconda3/envs/PY38/lib/python3.8/site-packages/simple_romp-1.1.3-py3.8-linux-x86_64.egg/trace2/main.py", line 13, in <module>
    from .models.model import TRACE_head
  File "/home/bihai/anaconda3/envs/PY38/lib/python3.8/site-packages/simple_romp-1.1.3-py3.8-linux-x86_64.egg/trace2/models/model.py", line 11, in <module>
    from .deform_conv import DeformConv
  File "/home/bihai/anaconda3/envs/PY38/lib/python3.8/site-packages/simple_romp-1.1.3-py3.8-linux-x86_64.egg/trace2/models/deform_conv/__init__.py", line 3, in <module>
    from .modules.deform_conv import (DeformConv, ModulatedDeformConv,
ModuleNotFoundError: No module named 'trace2.models.deform_conv.modules'
```

**Comment by Arthur151** [comment]
Please make sure that 
1. you have use the latest code from github. 
2. please install simple-romp for TRACE following this instruction:
https://github.com/Arthur151/ROMP/blob/master/simple_romp/trace2/README.md
It is different from the simple-romp for ROMP and BEV.

**Comment by bj4-567** [comment]
Hi， thanks for your great work,
I followed the installation steps you gave me to install trace2.
I can't success install deform conv. 
I google it and found out if it is because deform conv only supports the cuda10 environment.

This is my environment configuration
cuda 11.3 / pytorch1.12 / python3.8
Thanks, a lot.

**Comment by ChengDaTsai** [comment]
Hello , I have the same question in cuda11.3 !
So I need to downgrade to cuda10 to solve this problem : No module named 'deform_conv_cuda' ?

**Comment by Yamato-01** [comment]
@bj4-567 have you solve this problem？ I meet the same problem: `No module named 'trace2.models.deform_conv.modules'`

**Comment by dFuong** [comment]
> @TonyzBi Please make sure that
> 
> 1. you have use the latest code from github.
> 2. please install simple-romp for TRACE following this instruction:
>    https://github.com/Arthur151/ROMP/blob/master/simple_romp/trace2/README.md
>    It is different from the simple-romp for ROMP and BEV.

I follow your guide, but I also meet as same trouble 
![image](https://github.com/Arthur151/ROMP/assets/48349629/d83b38ce-a764-4aa6-b6ee-379b912ff7f0)

python 3.8 cuda-10.2

Please refer some suggestion!

**Comment by IsshikiHugh** [comment]
I got `No module named deform_conv_cuda` while I'm using python 3.8.17 & cuda 11.3, and I found this issue and try to downgrade the cuda version and get `No module named 'trace2.models.deform_conv.modules'` now. 

Has anyone solved this problem?

**Comment by IsshikiHugh** [comment]
> 

I just solve the problem.
Here is some key points:

1. CUDA 11x doesn't look to be supported, I finally use cu10.2.
2. Remember to update the CUDA environments, I mean `CUDA_HOME` and `LD_LIBRARY_PATH`.
3. Remove `build` folder under `simple_romp` and then run `python setup_trace install`.

**Comment by Miles629** [comment]
The support of 30 series and 40 series GPUs for CUDA 10.x seems to be incomplete, which means that to solve this problem, it is necessary to use 20 series GPUs or earlier.

Is there a way to solve this problem in the CUDA 11.x environment? I don't have a 20 series GPU.

**Comment by Miles629** [comment]
Hey, everyone. It seems that if we manually copy the 'trace2.models.deform_conv.modules' py files to the right env position. the problem will be solved!

But when running trace2, the output is
`alt_cuda_corr is not compiled `
but it seems doesn't meter for running.

**Comment by ramacha7** [comment]
@Miles629 what would be the right env position?

**Comment by ramacha7** [comment]
@FrankBu0616 did you have CUDA 11.3 or CUDA 10.2? Does it matter what cuda version this is? Or did you simply not care and just remove the build folder and rebuild?

**Comment by Miles629** [comment]
> be

Sorry. I forget it. I did it too long time ago.

**Comment by HsingyouZhou** [comment]
> Hey, everyone. It seems that if we manually copy the 'trace2.models.deform_conv.modules' py files to the right env position. the problem will be solved!
> 
> But when running trace2, the output is `alt_cuda_corr is not compiled ` but it seems doesn't meter for running.

I may find the route.

cd to 
`./ROMP/simple_romp/trace2/models/deform_conv`

and copy the dir `modules` to the trace2's env dir in the python's package directory, just like this:

`cp -r ./modules /usr/local/lib/python3.10/dist-packages/trace2/models/deform_conv`

then your python will detect the module named 'trace2.models.deform_conv.modules'
