### ISSUE TITLE
smil_packed_info.pth not found

### ISSUE THREAD

**Issue by JincanDeng** [Arthur151/ROMP#459]
Hi, thanks for your amazing work! I want to run a demo, but meeting the error says:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.romp/smil_packed_info.pth'.
Any advice for this?

**Comment by Arthur151** [comment]
@JincanDeng 
Please refer to [this instruction] to prepare the SMPL files:
https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation

**Comment by JincanDeng** [comment]
> @JincanDeng Please refer to [this instruction] to prepare the SMPL files: https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation

Thanks! I got it.

**Comment by ling-yue** [comment]
您好，根据您提供的github网址，我只找到了这几个文件
|   |-- J_regressor_extra.npy
|   |-- J_regressor_h36m.npy
|   |-- smpl_kid_template.npy
|   |-- smil
|   |-- |-- smil_web.pkl
没有找到以下几个
|   |-- SMPL_NEUTRAL.pth
|   |-- SMPLA_NEUTRAL.pth
|   |-- smil_packed_info.pth

**Comment by jsietbv** [comment]
您好，根据您提供的github网址，我只找到了这几个文件
| |-- J_regressor_extra.npy
| |-- J_regressor_h36m.npy
| |-- smpl_kid_template.npy
| |-- smil
| |-- |-- smil_web.pkl
没有找到以下几个
| |-- SMPL_NEUTRAL.pth
| |-- SMPLA_NEUTRAL.pth
| |-- smil_packed_info.pth

**Comment by Song-jinshui** [comment]
> 

俺也一样！

**Comment by Arthur151** [comment]
@jsietbv @Song-jinshui 
因为版权问题，剩下的文件只能通过以下说明来准备：
https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md
2.Preparing SMPL model files in our format:
。。。。

**Comment by Song-jinshui** [comment]
> > > @JincanDeng Please refer to [this instruction] to prepare the SMPL files: https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation
> > 
> > 
> > Thanks! I got it.
> 
> > @jsietbv @Song-jinshui 因为版权问题，剩下的文件只能通过以下说明来准备： https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md 2.Preparing SMPL model files in our format:
> > ```
> > please convert the SMPL model files to our format via
> > 
> > # please provide the absolute path of the "smpl_model_data" folder to the source_dir 
> > romp.prepare_smpl -source_dir=/path/to/smpl_model_data
> > # (Optional) If you use BEV, please also run:
> > bev.prepare_smil -source_dir=/path/to/smpl_model_data
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 。。。。
> 
> 谢谢！但是我运行romp.prepare_smpl -source_dir=/home/ly/smpl_model_data 获得了 SMPLA_NEUTRAL.pth 和SMPL_NEUTRAL.pth两个文件，请问smil_packed_info.pth是通过 运行bev.prepare_smil -source_dir=/home/ly/smpl_model_data产生的吗？但是我运行这个命令行报错： TypeError: `@validator(..., each_item=True)` cannot be applied to fields with a schema of json-or-python 请问这是什么原因呢，我在互联网上查询不到相关原因。

``(py37) ly@mit-338:~/.romp$ bev.prepare_smil -source_dir=/home/ly/smpl_model_data
Traceback (most recent call last):
  File "/home/ly/anaconda3/envs/py37/bin/bev.prepare_smil", line 5, in <module>
    from bev.pack_smil_info import main
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/bev/__init__.py", line 1, in <module>
    from .interface import Repository
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/bev/interface.py", line 10, in <module>
    from .config import CONFIG, build_storage, find_vcs_root
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/bev/config/__init__.py", line 1, in <module>
    from .base import *
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/bev/config/base.py", line 9, in <module>
    from .location import LocationConfig, NoExtra, from_special
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/bev/config/location.py", line 87, in <module>
    class LevelsConfig(LocationConfig):
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 177, in __new__
    types_namespace=types_namespace,
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 420, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/main.py", line 533, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 265, in generate_schema
    obj, from_dunder_get_core_schema=from_dunder_get_core_schema, from_prepare_args=from_prepare_args
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 285, in _generate_schema_for_type
    schema = self._generate_schema(obj)
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 475, in _generate_schema
    return self._model_schema(obj)
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 351, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 351, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 614, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 670, in _common_field_schema
    schema = apply_each_item_validators(schema, each_item_validators)
  File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 164, in apply_each_item_validators
    f"`@validator(..., each_item=True)` cannot be applied to fields with a schema of {schema['type']}"
TypeError: `@validator(..., each_item=True)` cannot be applied to fields with a schema of json-or-python

**Comment by Song-jinshui** [comment]
> > @JincanDeng Please refer to [this instruction] to prepare the SMPL files: https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation
> 
> Thanks! I got it.

Hello, did you get the smil_packed_info.pth by running bev.prepare_smil -source_dir=/path/to/smpl_model_data? Thank you.

**Comment by Arthur151** [comment]
@Song-jinshui 
Error here is really weird. 

As you can see in 
https://github.com/Arthur151/ROMP/blob/master/simple_romp/bev/__init__.py
there is no such a line, like 
```
File "/home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/bev/init.py", line 1, in
from .interface import Repository
```
which occurs this error. 

Please try to just delete this line via
```
gedit /home/ly/anaconda3/envs/py37/lib/python3.7/site-packages/bev/init.py
```
delete `from .interface import Repository`

I wonder where is this line from?

**Comment by JincanDeng** [comment]
> 

Yes, I successfully generate it by following: https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation.
The main instructions are: 
`# please provide the absolute path of the "smpl_model_data" folder to the source_dir 
romp.prepare_smpl -source_dir=/path/to/smpl_model_data
# (Optional) If you use BEV, please also run:
bev.prepare_smil -source_dir=/path/to/smpl_model_data`

**Comment by JincanDeng** [comment]
> > > @JincanDeng Please refer to [this instruction] to prepare the SMPL files: https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation
> > 
> > 
> > Thanks! I got it.
> 
> Hello, did you get the smil_packed_info.pth by running bev.prepare_smil -source_dir=/path/to/smpl_model_data? Thank you.

是的，可以自己生成需要的文件，主要参考： https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation.
中间可能需要做一些文件重命名的对齐。
