### ISSUE TITLE
KeyError: 'joints_smpl24'

### ISSUE THREAD

**Issue by neverstoplearn** [Arthur151/ROMP#486]
Traceback (most recent call last):
  File "/xxxx/ROMP/romp/lib/evaluation/collect_3DPW_results.py", line 212, in <module>
    submitor = Submit()
  File "/xxxx/ROMP/romp/lib/evaluation/collect_3DPW_results.py", line 26, in __init__
    self.evaluation()
  File "/xxxx/miniconda3/envs/torch10/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/xxxx/ROMP/romp/lib/evaluation/collect_3DPW_results.py", line 81, in evaluation
    kp3d_smpl = outputs['joints_smpl24']
KeyError: 'joints_smpl24'

how to fix it?

**Comment by Arthur151** [comment]
Sorry, I changed the name of the keys in outputs dict. 
You can print the key names in outputs and find the one fit the 'joints_smpl24'

**Comment by neverstoplearn** [comment]
> Sorry, I changed the name of the keys in outputs dict. You can print the key names in outputs and find the one fit the 'joints_smpl24'

thanks,I will try it.

**Comment by neverstoplearn** [comment]
@Arthur151 
the dict like this:
dict_keys(['params_maps', 'center_map', 'detection_flag', 'params_pred', 'reorganize_idx', 'centers_pred', 'params', 'verts', 'j3d', 'joints_h36m17', 'pj2d', 'cam_trans', 'verts_camed', 'pj2d_org', 'verts_camed_org', 'meta_data'])
which i should choose?

**Comment by GUI0809** [comment]
> [@Arthur151](https://github.com/Arthur151) the dict like this: dict_keys(['params_maps', 'center_map', 'detection_flag', 'params_pred', 'reorganize_idx', 'centers_pred', 'params', 'verts', 'j3d', 'joints_h36m17', 'pj2d', 'cam_trans', 'verts_camed', 'pj2d_org', 'verts_camed_org', 'meta_data']) which i should choose?

Hello! May I ask if you have solved this problem, and how exactly did you solve it?
