### ISSUE TITLE
EVAL  CMU dataset

### ISSUE THREAD

**Issue by neverstoplearn** [Arthur151/ROMP#489]
INFO:root:Training all layers.
Initialization finished!
INFO:root:gathering single image datasets.
INFO:root:CMU Panoptic dataset total 9600 samples, loading test split
AMASS dataset number of videos: 253310
Traceback (most recent call last):
  File "/egova_data/xxx/miniconda3/envs/torch10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/egova_data/xxx/miniconda3/envs/torch10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/egova_data/xxx/ROMP/romp/test.py", line 204, in <module>
    main()
  File "/egova_data/xxx/ROMP/romp/test.py", line 195, in main
    demo.test_cmu_panoptic()
  File "/egova_data/xxx/ROMP/romp/test.py", line 53, in test_cmu_panoptic
    for test_iter,meta_data in enumerate(data_loader):
  File "/egova_data/xxx/miniconda3/envs/torch10/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/egova_data/xxx/miniconda3/envs/torch10/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/egova_data/xxx/miniconda3/envs/torch10/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/egova_data/xxx/miniconda3/envs/torch10/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/egova_data/xxx/ROMP/romp/lib/models/../dataset/mixed_dataset.py", line 101, in __getitem__
    return self.dataset[index]
  File "/egova_data/xxx/ROMP/romp/lib/models/../dataset/image_base.py", line 487, in __getitem__
    return self.get_item_single_frame(index)
  File "/egova_data/xxx/ROMP/romp/lib/models/../dataset/image_base.py", line 117, in get_item_single_frame
    kp3d, valid_masks[:,1] = self.process_kp3ds(info['kp3ds'], used_person_inds, \
  File "/egova_data/xxx/ROMP/romp/lib/models/../dataset/image_base.py", line 359, in process_kp3ds
    kp3d_processed[inds] = kp3d
ValueError: could not broadcast input array from shape (17,3) into shape (54,3)

hwo to fix it?

**Comment by neverstoplearn** [comment]
AttributeError: 'Namespace' object has no attribute 'smpl_J_reg_h37m_path'

@Arthur151 where I can got this file?
