### ISSUE TITLE
can not find active_config folder

### ISSUE THREAD

**Issue by leon532** [Arthur151/ROMP#73]
Thanks for sharing your great job! 

The test script can not find the active_config folder. May I ask where can i find the active_config folder?

Traceback (most recent call last):
  File "/data00/liyang.1610/anaconda3/envs/romp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data00/liyang.1610/anaconda3/envs/romp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data00/liyang.1610/projects/ROMP/romp/predict/image.py", line 1, in <module>
    from .base_predictor import *
  File "/data00/liyang.1610/projects/ROMP/romp/predict/base_predictor.py", line 1, in <module>
    from ..base import *
  File "/data00/liyang.1610/projects/ROMP/romp/base.py", line 17, in <module>
    from models import build_model,build_teacher_model
  File "/data00/liyang.1610/projects/ROMP/romp/lib/models/__init__.py", line 1, in <module>
    from .build import build_model,build_teacher_model
  File "/data00/liyang.1610/projects/ROMP/romp/lib/models/build.py", line 8, in <module>
    from models.hrnet_32 import HigherResolutionNet
  File "/data00/liyang.1610/projects/ROMP/romp/lib/models/hrnet_32.py", line 19, in <module>
    from utils import BHWC_to_BCHW, copy_state_dict
  File "/data00/liyang.1610/projects/ROMP/romp/lib/models/../utils/__init__.py", line 7, in <module>
    from .center_utils import process_gt_center
  File "/data00/liyang.1610/projects/ROMP/romp/lib/models/../utils/center_utils.py", line 6, in <module>
    def denormalize_center(center, size=args().centermap_size):
  File "/data00/liyang.1610/projects/ROMP/romp/lib/config.py", line 244, in args
    with open(ConfigContext.yaml_filename, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data00/liyang.1610/projects/ROMP/active_configs/active_context_2021-09-13_16_17_33.yaml'

**Comment by Arthur151** [comment]
Thanks for the bug report. I have added the empty active_configs folder in the latest update
