### ISSUE TITLE
video test promblem

### ISSUE THREAD

**Issue by jiandandian2** [Arthur151/ROMP#99]
Dear Arthur151, when test video on your method, last frame always gets mistake, hope you reply.

this is issue:

pygame 2.0.0 (SDL 2.0.12, python 3.7.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/neu307/miniconda3/envs/env_centerhmr/lib/python3.7/site-packages/quaternion/numba_wrapper.py:21: UserWarning: 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Could not import from numba, which means that some
parts of this code may run MUCH more slowly.  You
may wish to install numba.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  warnings.warn(warning_text)
INFO - 2021-11-16 15:56:39,929 - acceleratesupport - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO - 2021-11-16 15:56:40,399 - base - {'tab': 'hrnet_cm64_test', 'configs_yml': 'configs/video.yml', 'demo_image_folder': 'None', 'local_rank': 0, 'model_version': 1, 'multi_person': True, 'collision_aware_centermap': False, 'collision_factor': 0.2, 'kp3d_format': 'smpl24', 'eval': False, 'max_person': 64, 'input_size': 512, 'Rot_type': '6D', 'rot_dim': 6, 'centermap_conf_thresh': 0.25, 'centermap_size': 64, 'deconv_num': 0, 'model_precision': 'fp32', 'backbone': 'hrnet', 'gmodel_path': '../trained_models/ROMP_hrnet32.pkl', 'print_freq': 50, 'fine_tune': True, 'gpu': '0', 'batch_size': 64, 'val_batch_size': 1, 'nw': 4, 'calc_PVE_error': False, 'dataset_rootdir': '/home/neu307/wh/dataset/', 'high_resolution': True, 'save_best_folder': '/home/neu307/wh/checkpoints/', 'log_path': '/home/neu307/wh/log/', 'total_param_count': 85, 'smpl_mean_param_path': '/home/neu307/wh/ROMP-master/models/satistic_data/neutral_smpl_mean_params.h5', 'smpl_model': '/home/neu307/wh/ROMP-master/models/statistic_data/neutral_smpl_with_cocoplus_reg.txt', 'smplx_model': True, 'cam_dim': 3, 'beta_dim': 10, 'smpl_joint_num': 22, 'smpl_model_path': '/home/neu307/wh/ROMP-master/models', 'smpl_uvmap': '/home/neu307/wh/ROMP-master/models/smpl/uv_table.npy', 'smpl_female_texture': '/home/neu307/wh/ROMP-master/models/smpl/SMPL_sampleTex_f.jpg', 'smpl_male_texture': '/home/neu307/wh/ROMP-master/models/smpl/SMPL_sampleTex_m.jpg', 'smpl_J_reg_h37m_path': '/home/neu307/wh/ROMP-master/models/smpl/J_regressor_h36m.npy', 'smpl_J_reg_extra_path': '/home/neu307/wh/ROMP-master/models/smpl/J_regressor_extra.npy', 'kernel_sizes': [5], 'GPUS': 0, 'use_coordmaps': True, 'video_or_frame': True, 'input_video_path': '../demo/test_videos/C1/C1_single_2.mp4', 'webcam_mesh_color': 'LightCyan', 'save_mesh': False, 'save_centermap': False, 'save_dict_results': True, 'webcam': False, 'fps_save': 30, 'multiprocess': False}
INFO - 2021-11-16 15:56:40,399 - base - ------------------------------------------------------------------
INFO - 2021-11-16 15:56:40,399 - base - start building model.
Using ROMP v1
INFO - 2021-11-16 15:56:43,931 - train_utils - using fine_tune model: ../trained_models/ROMP_hrnet32.pkl
INFO - 2021-11-16 15:56:44,085 - base - finished build model.
Initialization finished!
Running the code on video  ../demo/test_videos/C1/C1_single_2.mp4
Processing video 0/164
Processing video 1/164
Processing video 2/164
Processing video 3/164
Processing video 4/164
Processing video 5/164
Processing video 6/164
Processing video 7/164
Processing video 8/164
Processing video 9/164
Processing video 10/164
Processing video 11/164
Processing video 12/164
Processing video 13/164
Processing video 14/164
Processing video 15/164
Processing video 16/164
Processing video 17/164
Processing video 18/164
Processing video 19/164
Processing video 20/164
Processing video 21/164
Processing video 22/164
Processing video 23/164
Processing video 24/164
Processing video 25/164
Processing video 26/164
Processing video 27/164
Processing video 28/164
Processing video 29/164
Processing video 30/164
Processing video 31/164
Processing video 32/164
Processing video 33/164
Processing video 34/164
Processing video 35/164
Processing video 36/164
Processing video 37/164
Processing video 38/164
Processing video 39/164
Processing video 40/164
Processing video 41/164
Processing video 42/164
Processing video 43/164
Processing video 44/164
Processing video 45/164
Processing video 46/164
Processing video 47/164
Processing video 48/164
Processing video 49/164
Processing video 50/164
Processing video 51/164
Processing video 52/164
Processing video 53/164
Processing video 54/164
Processing video 55/164
Processing video 56/164
Processing video 57/164
Processing video 58/164
Processing video 59/164
Processing video 60/164
Processing video 61/164
Processing video 62/164
Processing video 63/164
Processing video 64/164
Processing video 65/164
Processing video 66/164
Processing video 67/164
Processing video 68/164
Processing video 69/164
Processing video 70/164
Processing video 71/164
Processing video 72/164
Processing video 73/164
Processing video 74/164
Processing video 75/164
Processing video 76/164
Processing video 77/164
Processing video 78/164
Processing video 79/164
Processing video 80/164
Processing video 81/164
Processing video 82/164
Processing video 83/164
Processing video 84/164
Processing video 85/164
Processing video 86/164
Processing video 87/164
Processing video 88/164
Processing video 89/164
Processing video 90/164
Processing video 91/164
Processing video 92/164
Processing video 93/164
Processing video 94/164
Processing video 95/164
Processing video 96/164
Processing video 97/164
Processing video 98/164
Processing video 99/164
Processing video 100/164
Processing video 101/164
Processing video 102/164
Processing video 103/164
Processing video 104/164
Processing video 105/164
Processing video 106/164
Processing video 107/164
Processing video 108/164
Processing video 109/164
Processing video 110/164
Processing video 111/164
Processing video 112/164
Processing video 113/164
Processing video 114/164
Processing video 115/164
Processing video 116/164
Processing video 117/164
Processing video 118/164
Processing video 119/164
Processing video 120/164
Processing video 121/164
Processing video 122/164
Processing video 123/164
Processing video 124/164
Processing video 125/164
Processing video 126/164
Processing video 127/164
Processing video 128/164
Processing video 129/164
Processing video 130/164
Processing video 131/164
Processing video 132/164
Processing video 133/164
Processing video 134/164
Processing video 135/164
Processing video 136/164
Processing video 137/164
Processing video 138/164
Processing video 139/164
Processing video 140/164
Processing video 141/164
Processing video 142/164
Processing video 143/164
Processing video 144/164
Processing video 145/164
Processing video 146/164
Processing video 147/164
Processing video 148/164
Processing video 149/164
Processing video 150/164
Processing video 151/164
Processing video 152/164
Processing video 153/164
Processing video 154/164
Processing video 155/164
Processing video 156/164
Processing video 157/164
Processing video 158/164
Processing video 159/164
Processing video 160/164
Traceback (most recent call last):
  File "/home/neu307/wh/ROMP-master/src/core/test.py", line 235, in <module>
    main()
  File "/home/neu307/wh/ROMP-master/src/core/test.py", line 224, in main
    demo.process_video(args.input_video_path)
  File "/home/neu307/wh/ROMP-master/src/core/test.py", line 114, in process_video
    outputs = self.single_image_forward(frame)
  File "/home/neu307/wh/ROMP-master/src/core/test.py", line 98, in single_image_forward
    meta_data = img_preprocess(image, '0', input_size=args.input_size, single_img_input=True)
  File "/home/neu307/wh/ROMP-master/src/core/../lib/models/../utils/demo_utils.py", line 31, in img_preprocess
    image = image[:,:,::-1]
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by Arthur151** [comment]
Sorry about that. 
I guess you are running code on a computer with multiple GPUs.
Please run code with 
"CUDA_VISIBLE_DEVICES=0 "
For instance, when you run it in processing video, please run it via
`CUDA_VISIBLE_DEVICES=0 python -u -m romp.predict.video --configs_yml='configs/video.yml'`

**Comment by jiandandian2** [comment]
> Sorry about that. I guess you are running code on a computer with multiple GPUs. Please run code with "CUDA_VISIBLE_DEVICES=0 " For instance, when you run it in processing video, please run it via `CUDA_VISIBLE_DEVICES=0 python -u -m romp.predict.video --configs_yml='configs/video.yml'`

<img width="1307" alt="屏幕快照 2021-11-16 下午7 28 38" src="https://user-images.githubusercontent.com/33227739/141977527-6758dd4d-a9a9-4de7-a051-d64e222496d6.png">

i run it on pycharm, have setted the cuda=0

**Comment by Arthur151** [comment]
Then that would be pretty weird.
I am chasing for a deadline now, for now, you use `try except` + `repeat the last few frame` to make it pass.
After the deadline, I will look into it. 
Is this ok?

**Comment by jiandandian2** [comment]
> Then that would be pretty weird. I am chasing for a deadline now. For now, you may use `try except` + `repeat the last few frame` to make it pass. After the deadline, I will look into it. Is this ok?

thank you, i will try

**Comment by jiandandian2** [comment]
![屏幕快照 2021-11-16 下午10 09 59](https://user-images.githubusercontent.com/33227739/142000855-df72761c-a14f-4763-8d5a-8c589df3ebe4.png)

I add try-except, and it works. Thank u

**Comment by Arthur151** [comment]
My appologize to the unpleasant back. 
I will get back to this later! Please remind me of this if you are in a hurry.

**Comment by Arthur151** [comment]
@jiandandian2 I am back to this issue.
I have just updated a new version of ROMP.
I just test it with processing 161/162/163/164 frames. It works fine. 
Could you please try it now?
